'use strict';
const fs=require('node:fs'), path=require('node:path'), {randomUUID}=require('node:crypto');
const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ChannelType,PermissionsBitField,ApplicationCommandOptionType:T}=require('discord.js');
const dir=path.join(__dirname,'avances'), config=path.join(__dirname,'novedades-canal.json'), ledger=path.join(dir,'publicaciones.json');
const views=new Map();
const commands=[{name:'avances',description:'Revisá y publicá los avances que preparamos para la comunidad',default_member_permissions:'8',dm_permission:false,options:[{name:'canal',description:'Elegí el destino solo la primera vez',type:T.Channel,channel_types:[ChannelType.GuildText,ChannelType.GuildAnnouncement]}]}];
function read(file, fallback){try {if(fs.statSync(file).size>1048576)throw Error('Archivo demasiado grande.');return JSON.parse(fs.readFileSync(file,'utf8'))}catch(e){if(e.code==='ENOENT')return fallback;throw Error('No se pudo leer la bandeja de avances.')}}
function write(file,data){fs.mkdirSync(dir,{recursive:true});const tmp=file+'.'+randomUUID()+'.tmp';fs.writeFileSync(tmp,JSON.stringify(data,null,2));try{fs.renameSync(tmp,file)}finally{if(fs.existsSync(tmp))fs.unlinkSync(tmp)}}
function news(){if(!fs.existsSync(dir))return[];const result=[];for(const file of fs.readdirSync(dir).filter(n=>n.endsWith('.json')&&n!=='publicaciones.json').sort()){const rows=read(path.join(dir,file),[]);if(!Array.isArray(rows))throw Error('El paquete de avances no es válido.');for(const n of rows){if(!/^[a-z0-9_-]{1,80}$/.test(n.id)||typeof n.title!=='string'||!n.title.trim()||n.title.length>150||typeof n.text!=='string'||!n.text.trim()||n.text.length>3500)throw Error('Un avance tiene un formato inválido.');const old=result.find(r=>r.id===n.id);if(old){if(old.title!==n.title||old.text!==n.text)throw Error('Hay versiones distintas del mismo avance.');continue}result.push(n)}}return result;}
async function destination(i,id){const c=await i.guild.channels.fetch(id);if(!c||c.guildId!==i.guildId||![ChannelType.GuildText,ChannelType.GuildAnnouncement].includes(c.type)||/estado/.test(c.name)||c.name==='comandos-bot')throw Error('Elegí un canal de avances o novedades.');const me=await i.guild.members.fetchMe();if(!c.permissionsFor(me)?.has([PermissionsBitField.Flags.ViewChannel,PermissionsBitField.Flags.SendMessages,PermissionsBitField.Flags.EmbedLinks]))throw Error('Al bot le faltan permisos en ese canal.');const member=await i.guild.members.fetch(i.user.id);if(!member.permissions.has(PermissionsBitField.Flags.Administrator))throw Error('Solo administradores pueden publicar avances.');return c;}
async function handle(i){const command=i.isChatInputCommand()&&i.commandName==='avances', button=i.isButton()&&i.customId.startsWith('mu_advance:');if(!command&&!button)return false;
try{
 if(i.guildId!==process.env.GUILD_ID||!i.memberPermissions?.has(PermissionsBitField.Flags.Administrator)){await i.reply({content:'Esta función es solo para administradores.',ephemeral:true});return true}
 for(const [id,v] of views)if(Date.now()-v.created>600000)views.delete(id);
 if(command){await i.deferReply({ephemeral:true});let syncFailed=false;try{await require('./avances-remote').refresh()}catch(e){syncFailed=true;console.error('[Avances] Se usa la copia local:',e.message)}const state=read(ledger,{});const pending=news().filter(n=>!state[n.id]);if(!pending.length){await i.editReply({content:syncFailed?'No pude actualizar la fuente de avances. En la copia local no hay anuncios pendientes. Intentá /avances nuevamente en un momento.':'Fuente actualizada: no hay avances nuevos pendientes. Los enviados no se vuelven a publicar.',components:[],embeds:[]});return true}
 let conf=read(config,{});const selected=i.options.getChannel('canal');if(selected){await destination(i,selected.id);conf={guild:i.guildId,channel:selected.id};write(config,conf)}
 if(conf.guild!==i.guildId||!conf.channel)throw Error('Usá /avances y elegí el campo canal una sola vez.');const c=await destination(i,conf.channel);const n=pending[0];const id=randomUUID();if(views.size>=100)throw Error('Hay demasiadas vistas abiertas.');views.set(id,{owner:i.user.id,guild:i.guildId,channel:c.id,news:n,created:Date.now(),state:'preview'});
 const embed=new EmbedBuilder().setAuthor({name:'MU PANIC · AVANCES'}).setTitle(n.title).setDescription(n.text).setColor(0xc9a64b).setFooter({text:'MU PANIC • En desarrollo rumbo a la apertura'});
 const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('mu_advance:publish:'+id).setLabel('Publicar este avance').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('mu_advance:cancel:'+id).setLabel('Dejar pendiente').setStyle(ButtonStyle.Secondary));
 await i.editReply({content:`**Avance listo para publicar** · <#${c.id}>\n${pending.length} pendiente(s). Esta vista es privada.`,embeds:[embed],components:[row],allowedMentions:{parse:[]}});
 }else{const [,action,id]=i.customId.split(':');const v=views.get(id);if(!v||v.owner!==i.user.id||v.guild!==i.guildId||v.state!=='preview'||!['publish','cancel'].includes(action))throw Error('Esta vista venció o ya se procesó. Usá /avances.');v.state='processing';await i.deferUpdate();if(action==='cancel'){views.delete(id);await i.editReply({content:'Queda pendiente. Podés volver a verlo con /avances.',embeds:[],components:[]});return true}
 const c=await destination(i,v.channel);const state=read(ledger,{});if(state[v.news.id])throw Error('Este avance ya se envió o tiene un envío pendiente de comprobar.');
 // Se guarda antes de enviar: un reinicio o un error de red no provoca reenvíos.
 state[v.news.id]={state:'sending',channel:c.id,actor:i.user.id,at:new Date().toISOString()};write(ledger,state);
 const embed=new EmbedBuilder().setAuthor({name:'MU PANIC · AVANCES'}).setTitle(v.news.title).setDescription(v.news.text).setColor(0xc9a64b).setFooter({text:'MU PANIC • En desarrollo rumbo a la apertura'});
 let sent;try{sent=await c.send({embeds:[embed],allowedMentions:{parse:[]}})}catch(e){console.error('[Avances] Envío no confirmado:',e.message);throw Error('No se pudo confirmar el envío. Revisá el canal; quedó bloqueado el reenvío para evitar duplicados.')}
 const latest=read(ledger,{});latest[v.news.id]={...state[v.news.id],state:'published',message:sent.id,url:sent.url};write(ledger,latest);views.delete(id);await i.editReply({content:`Publicado: ${sent.url}`,embeds:[],components:[]});
 }
}catch(e){console.error('[Avances]',e.message);const p={content:e.message,embeds:[],components:[],allowedMentions:{parse:[]}};if(i.deferred||i.replied)await i.editReply(p).catch(()=>{});else await i.reply({...p,ephemeral:true}).catch(()=>{})}return true}
require('./avances-remote').start();
module.exports={commands,handle};
