const fs=require('fs'),path=require('path'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'../overlay/templates/mupanic');
function render(module='',state='normal'){const html=execFileSync(process.env.PHP_BIN||'php',[path.join(__dirname,'fixtures/account.php')],{encoding:'utf8',env:{...process.env,ACCOUNT_MODULE:module,ACCOUNT_STATE:state}});if(/(?:Fatal error|Warning:|Notice:)/.test(html))throw Error('PHP fixture error '+module+' '+html.slice(-900));return html;}
const forms=()=>[...document.querySelector('.module-surface').querySelectorAll('form')].map(form=>({action:form.getAttribute('action'),method:form.method,data:[...new FormData(form)],buttons:[...document.querySelectorAll('button,input[type=submit]')].filter(b=>b.form===form).map(b=>({name:b.name,value:b.value,data:[...new FormData(form,b)]})),fields:[...form.elements].map(e=>({name:e.name,value:e.value,min:e.min,max:e.max,step:e.step,type:e.type,disabled:e.disabled}))}));
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_BIN,headless:true,args:['--no-sandbox']});
for(const width of (process.env.ACCOUNT_WIDTHS?JSON.parse(process.env.ACCOUNT_WIDTHS):[1440,1024,768,390,320]))for(const module of (process.env.ACCOUNT_MODULES?JSON.parse(process.env.ACCOUNT_MODULES):['','myaccount','reset','resetstats','clearpk','clearskilltree','unstick','addstats','myemail','mypassword','vote'])){
 const page=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce'});const errors=[];let enhance=false;page.on('pageerror',e=>errors.push(e.message));
 const html=render(module);
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.pathname==='/bootstrap-3.4.1.css')return route.fulfill({path:path.join(__dirname,'fixtures/bootstrap-3.4.1.css')});if(u.pathname.startsWith('/beta/usercp/'))return route.fulfill({contentType:'text/html',body:html});const prefix='/beta/templates/mupanic/';if(u.pathname===prefix+'js/account.js'&&!enhance)return route.fulfill({contentType:'text/javascript',body:''});if(/\/(?:online|offline)\.png$/.test(u.pathname))return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"/>'});if(u.pathname.startsWith(prefix)){const file=path.join(root,u.pathname.slice(prefix.length));if(fs.existsSync(file))return route.fulfill({path:file});}errors.push('Missing '+u.pathname);return route.abort();});
 await page.goto('https://preview.test/beta/usercp/'+module+'/',{waitUntil:'networkidle'});const before=await page.evaluate(forms);enhance=true;await page.addScriptTag({url:'https://preview.test/beta/templates/mupanic/js/account.js'});const after=await page.evaluate(forms);
 if(JSON.stringify(before)!==JSON.stringify(after))throw Error('Native form contract changed '+module+' '+JSON.stringify({before,after}));
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)||errors.length)throw Error(JSON.stringify({width,module,errors,overflow:true}));
 if(['reset','resetstats','clearpk','clearskilltree','unstick'].includes(module)) {const data=after.flatMap(f=>f.buttons.map(b=>b.data));if(data.length!==2||data[0].find(x=>x[0]==='character')?.[1]!=='TestDK'||data[1].find(x=>x[0]==='character')?.[1]!=='TestDL')throw Error('Character association broken');if(width<=600 && await page.locator('.general-table-ui tr').nth(1).evaluate(e=>getComputedStyle(e).display)!=='grid')throw Error('Mobile table not cards');}
 if(width<=900){const toggle=page.locator('.account-nav-toggle');if(await page.locator('.account-nav nav').isVisible())throw Error('Mobile menu starts expanded');await toggle.click();if(!await page.locator('.account-nav nav').isVisible()||await toggle.getAttribute('aria-expanded')!=='true')throw Error('Mobile navigation inaccessible');await toggle.click();}
 if(!module){if(!(await page.locator('.account-live-metrics').textContent()).includes('15.000')||await page.locator('.account-roster-card').count()!==2)throw Error('Dashboard data wrong');if(await page.locator('.account-vip-campaign').count()!==1)throw Error('VIP promo missing');}
 if(process.env.ACCOUNT_SCREENSHOT_DIR && ['', 'reset','mypassword','addstats'].includes(module) && [1440,390].includes(width)){fs.mkdirSync(process.env.ACCOUNT_SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.ACCOUNT_SCREENSHOT_DIR,(module||'home')+'-'+width+'.png'),fullPage:true});}
 await page.close();
}for(const state of ['active','unknown','empty']){const html=render('',state);if(state==='active'&&!html.includes('12 días restantes'))throw Error('Active VIP missing');if(state==='unknown'&&!html.includes('No disponible'))throw Error('Unknown converted to zero');if(state==='empty'&&!html.includes('Creá tu primer personaje'))throw Error('Empty account misleading');}
console.log('Account dashboard and 10 native modules: 5 widths, canonical FormData/submitters/limits, mobile cards/navigation, SQL states passed. No account operations submitted.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
