<?php if(!defined('access') || !access) die();
require_once(__DIR__.'/atlas-event-runtime.php');
$eventSnapshot=panicAtlasEvents();
$atlasEvents=array_values(array_filter($eventSnapshot['events'],function($e){return $e['enabled'];}));
$eventGroups=['classic'=>'Clásicos','custom'=>'Competencias','boss'=>'Desafíos','invasion'=>'Invasiones','staff'=>'Organizados'];
$eventStories=[
 'blood-castle'=>['Abrí el camino. Recuperá el objetivo.','Avanzá por el puente, recuperá el arma del ángel y devolvela antes del cierre.','Con una Invisibility Cloak de la categoría habilitada en el cliente.','Abrir paso hacia la fortaleza y completar la entrega.'],
 'devil-square'=>['Las oleadas no esperan. Tu party tampoco.','Una arena de monstruos: prepará tu personaje, resistí el combate y sumá puntos durante las oleadas.','Con una Devil’s Invitation de la categoría habilitada en el cliente.','Sobrevivir y sumar puntos derrotando criaturas.'],
 'chaos-castle'=>['Cada paso puede decidir la batalla.','Un desafío de supervivencia en Chaos Castle. Revisá en el cliente tu categoría y las condiciones de entrada.','Con Armor of Guardsman; consultá la categoría en el cliente.','Sobrevivir a los rivales y monstruos de la arena.'],
 'illusion-temple'=>['La estrategia también conquista.','Competí por equipos en Illusion Temple. Coordiná tus movimientos y disputá el objetivo de la arena.','Consultá la entrada y categoría en la interfaz del evento.','Disputar el objetivo con tu equipo.'],
 'double-goer'=>['Una defensa que exige sostener la línea.','Una instancia de combate con dificultad configurada por el servidor. Prepará recursos y coordiná el avance de tu grupo.','Acceso por la interfaz del evento dentro del juego.','Completar el desafío antes del cierre.'],
 'imperial-guardian'=>['La fortaleza espera a tu grupo.','Recorré el desafío de Imperial Guardian y enfrentá sus enemigos. El acceso depende de las condiciones mostradas por el cliente.','Consultá los requisitos de la instancia dentro del juego.','Completar el recorrido y enfrentar al jefe.'],
 'kanturu'=>['El desafío vive en las ruinas.','Kanturu combina combate y fases propias del escenario. Su disponibilidad depende del ciclo de la instancia.','En el acceso del evento, dentro de Kanturu.','Superar las fases del desafío.'],
 'raklion'=>['LaCleon esconde una amenaza mayor.','El sistema de Raklion habilita el enfrentamiento con Selupan en LaCleon. El encuentro depende de las condiciones de la zona.','En la zona del boss dentro de LaCleon.','Enfrentar a Selupan.'],
 'pandora'=>['Conseguí el objeto. Defendé la conquista.','Caza del Maldito es la competencia basada en Pandora: disputá el objeto del evento y conservá su posesión hasta el cierre.','Seguí el anuncio del evento dentro del juego.','Conseguir el objeto y defenderlo hasta el final.'],
 'tvt'=>['Dos equipos. Una misma arena.','Una competencia Team vs Team con equipos enfrentados. Seguí la inscripción y los anuncios del cliente.','Desde el NPC de inscripción del evento.','Competir junto a tu equipo.'],
 'gvg'=>['Tu guild entra en la disputa.','Una competencia entre guilds habilitada en la configuración del servidor. Organizá tu grupo y seguí el anuncio de inscripción.','Desde el NPC de inscripción del evento.','Competir junto a tu guild.'],
 'battle-royale'=>['Entrá en la arena. Buscá sobrevivir.','Una competencia Battle Royale con condiciones propias del servidor. Revisá las reglas anunciadas al ingresar.','Desde el NPC de inscripción del evento.','Superar a tus rivales dentro de la arena.'],
 'demon-guardian'=>['La defensa se convierte en batalla.','Dos bandos compiten en Demon Guardian. Prepará tu equipo y seguí los objetivos anunciados dentro del evento.','Desde el NPC de inscripción del evento.','Cumplir el objetivo de tu bando.'],
 'king-of-mu'=>['Una conquista para tu guild.','King of MU es una disputa entre guilds. Reuní a tu grupo y seguí las indicaciones del evento dentro del juego.','Seguí el anuncio y acudí al lugar indicado.','Participar en la disputa con tu guild.'],
 'marathon'=>['Cada etapa abre el siguiente destino.','Un recorrido por etapas con requisitos configurados: movimientos, objetos y objetivos de combate.','Seguí los anuncios y las etapas dentro del juego.','Completar los objetivos de cada etapa.'],
 'pvp-championship'=>['Un torneo para medir tu dominio.','Un campeonato PvP con categorías configuradas por el servidor. Consultá en la inscripción cuál corresponde a tu personaje.','Desde el NPC de inscripción del campeonato.','Avanzar en los enfrentamientos de tu categoría.'],
 'moss'=>['Una visita que abre nuevas posibilidades.','Moss Merchant aparece según la agenda del servidor. Sus intercambios y condiciones se consultan directamente con el NPC.','Buscá al comerciante cuando se anuncie su aparición.','Consultar las opciones disponibles con el NPC.']
];
$modeNames=['scheduled'=>'Programado','access'=>'Por acceso / condiciones','manual'=>'Organizado por staff'];
$dayNames=['','Dom','Lun','Mar','Mié','Jue','Vie','Sáb'];
$eventHours=function($e) use($dayNames) {
 if(!$e['schedule']) return $e['mode']==='manual' ? 'Se anuncia dentro del juego.' : 'Sin horario fijo; depende del acceso o del ciclo del escenario.';
 $labels=[];
 foreach($e['schedule'] as $r) {
  $label=($r[4]<0?'Cada hora · ':str_pad($r[4],2,'0',STR_PAD_LEFT).':').str_pad(max(0,$r[5]),2,'0',STR_PAD_LEFT);
  if($r[3]>0) $label.=' · '.$dayNames[$r[3]];
  if($r[2]>0 || $r[1]>0 || $r[0]>0) $label.=' · fecha específica';
  $labels[$label]=true;
 }
 $all=array_keys($labels);return implode(' · ',array_slice($all,0,6)).(count($all)>6?' · +'.(count($all)-6).' horarios en la agenda':'');
};
$eventImage=function($e) use($atlasAssets) {
 if(in_array($e['id'],['blood-castle','devil-square','pandora'],true)) return 'img/atlas/editorial/'.$e['id'].'.webp';
 foreach($e['monsters'] as $mid) if(isset($atlasAssets['monsters'][(string)$mid])) return $atlasAssets['monsters'][(string)$mid]['file'];
 if($e['id']==='raklion' && isset($atlasAssets['monsters']['459'])) return $atlasAssets['monsters']['459']['file'];
 return 'img/atlas/editorial/'.($e['group']==='classic'?'imperial-temple':($e['group']==='boss'?'devil-square':'pvp-arena')).'.webp';
};
?>
<section id="eventos" class="wiki-section" aria-labelledby="atlas-events-title" data-events-version="<?php echo $eventSnapshot['sourceHash']; ?>">
 <div class="atlas-section-heading"><div><span class="eyebrow">EL CONTINENTE NO SE DETIENE</span><h2 id="atlas-events-title">Respondé al desafío.</h2></div><span class="atlas-section-mark" aria-hidden="true">III</span></div>
 <p>Elegí tu próxima batalla. Conocé el objetivo, los horarios y qué podés conseguir.</p>
 <div class="atlas-agenda"><div class="atlas-agenda-head"><h3>Próximos desafíos</h3><span>Hora Argentina<br>UTC−3</span></div><div data-event-upcoming><p>Los horarios completos están disponibles debajo.</p></div><details class="atlas-full-agenda"><summary>Consultar todos los horarios</summary><?php foreach($atlasEvents as $e) { if(!$e['schedule']) continue; ?><div class="atlas-agenda-entry"><span><?php echo panicWikiEscape($e['name']); ?></span><div><?php foreach($e['schedule'] as $r) { ?><small><?php echo panicWikiEscape(($r[3]>0?$dayNames[$r[3]].' ':'').($r[4]<0?'Cada hora · ':str_pad($r[4],2,'0',STR_PAD_LEFT).':').str_pad(max(0,$r[5]),2,'0',STR_PAD_LEFT).($r[2]>0?' · día '.$r[2]:'').($r[1]>0?' · mes '.$r[1]:'').($r[0]>0?' · '.$r[0]:'')); ?></small><?php } ?></div></div><?php } ?></details><p class="atlas-agenda-note">Agenda prevista: confirmá la apertura con los avisos del juego. Los eventos por acceso y los organizados se anuncian dentro del cliente. Actualizado: <time datetime="<?php echo panicWikiEscape($eventSnapshot['generatedAt']); ?>" data-event-published></time></p></div>
 <div class="atlas-event-controls" aria-label="Filtrar eventos"><button type="button" data-event-group="all" aria-pressed="true">Todos <span><?php echo count($atlasEvents); ?></span></button><?php foreach($eventGroups as $key=>$label) { ?><button type="button" data-event-group="<?php echo $key; ?>" aria-pressed="false"><?php echo $label; ?></button><?php } ?><label><span class="sr-only">Buscar evento</span><input type="search" data-event-search placeholder="Buscar evento…"></label></div><p data-event-empty hidden>No hay eventos habilitados para esta búsqueda.</p>
 <div class="atlas-event-grid"><?php foreach($atlasEvents as $e) { $story=$eventStories[$e['id']] ?? null; ?><article class="atlas-event-card" data-event-kind="<?php echo $e['group']; ?>" data-event-name="<?php echo panicWikiEscape($e['name']); ?>"><img loading="lazy" width="640" height="360" src="<?php echo __PATH_TEMPLATE__.panicWikiEscape($eventImage($e)); ?>" alt=""><div><span class="eyebrow"><?php echo $eventGroups[$e['group']]; ?></span><h3><?php echo panicWikiEscape($e['name']); ?></h3><p><?php echo panicWikiEscape($story[0] ?? ($e['group']==='invasion'?'La amenaza llega al continente.':'Un desafío anunciado dentro del juego.')); ?></p><span class="atlas-event-status"><?php echo $modeNames[$e['mode']]; ?></span><a href="#evento-<?php echo $e['id']; ?>" data-atlas-event-open="<?php echo $e['id']; ?>">Conocer el evento →</a></div></article><?php } ?></div>
 <?php foreach($atlasEvents as $e) {
  $story=$eventStories[$e['id']] ?? (strpos($e['id'],'arena-')===0 ? ['','Una arena con reglas propias de participación. Revisá los requisitos de tu personaje y seguí la convocatoria del evento.','Consultá el acceso y los requisitos de la arena dentro del cliente.','Competir según las reglas de la arena.'] : (strpos($e['id'],'event-drop-')===0 ? ['','Una lluvia de objetos en el escenario anunciado por el juego. Los premios aparecen durante el tiempo del evento.','Acudí al mapa indicado en los anuncios del evento.','Buscar los objetos que aparecen durante la lluvia.'] : ($e['group']==='invasion' ? ['','Una invasión programada: seguí el anuncio, buscá a las criaturas en los mapas del evento y preparate para el combate.','Seguí el anuncio de invasión dentro del juego.','Buscar y derrotar a los monstruos de la invasión.'] : ['','Un evento habilitado para ser organizado dentro del juego. La convocatoria y las reglas se anuncian al iniciarlo.','Esperá la convocatoria del staff.','Seguí las reglas anunciadas durante la convocatoria.'])));
  $facts=['Cómo participar'=>$story[2],'Tu objetivo'=>$story[3],'Duración'=>$e['durationMinutes']?$e['durationMinutes'].' minutos configurados.':'Depende de las fases o condiciones del evento.','Horarios'=>$eventHours($e)];
  $rewardNames=$e['items'];foreach($wiki['eventBags'] ?? [] as $bag) if(in_array($bag['id'],$e['bags'],true) && !$e['items']) foreach($bag['items'] as $item) $rewardNames[$item['name']]=$item['name'];
  $rewardNames=array_values(array_unique($rewardNames));$rewards=$rewardNames?implode(' · ',array_slice($rewardNames,0,4)).(count($rewardNames)>4?' · más objetos en las listas.':''):'Consultá las condiciones de recompensa dentro del evento.';
  foreach($e['coins'] as $coin) { $values=[];foreach(['WCoin C','WCoin P','Goblin Points'] as $i=>$name) if($coin[$i]) $values[]=$coin[$i].' '.$name;$rewards.=' · '.implode(' / ',$values).' según resultado/categoría.'; }
 ?>
 <article id="evento-<?php echo $e['id']; ?>" class="atlas-event-full" data-atlas-event="<?php echo $e['id']; ?>"><div class="atlas-event-dossier"><div class="atlas-event-visual"><img loading="lazy" width="640" height="960" src="<?php echo __PATH_TEMPLATE__.panicWikiEscape($eventImage($e)); ?>" alt=""><span aria-hidden="true"><?php echo panicWikiEscape($e['name']); ?></span></div><div class="atlas-event-copy"><span class="eyebrow"><?php echo $eventGroups[$e['group']].' / '.$modeNames[$e['mode']]; ?></span><h3><?php echo panicWikiEscape($e['name']); ?></h3><p><?php echo panicWikiEscape($story[1]); ?></p><dl class="atlas-event-facts"><?php foreach($facts as $label=>$value) { ?><div><dt><?php echo panicWikiEscape($label); ?></dt><dd><?php echo panicWikiEscape($value); ?></dd></div><?php } ?></dl><div class="atlas-event-rewards"><strong>Qué podés conseguir</strong><?php echo panicWikiEscape($rewards); ?><?php if($e['bags']) { ?><div class="atlas-event-tiers"><?php foreach(array_slice($e['bags'],0,8) as $i=>$bid) { ?><a href="#recompensa-<?php echo $bid; ?>">Lista <?php echo $i+1; ?> ↗</a><?php } ?></div><?php } ?></div><p class="atlas-event-footnote">Los objetos listados son posibilidades, no una entrega garantizada de todos ellos. Ilustración conceptual o recurso del cliente; no es una captura de la interfaz.</p></div></div></article>
 <?php } ?>
 <script type="application/json" data-event-data><?php echo json_encode($eventSnapshot,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT); ?></script>
</section>
<dialog class="atlas-event-dialog" data-atlas-event-dialog aria-label="Detalles del evento"><button class="atlas-event-close" type="button" data-atlas-event-close aria-label="Cerrar evento">×</button><div data-atlas-event-content></div></dialog>
