<?php if(!defined('access') || !access) die();
// Editorial mechanics are separate from live reward tables. No assumed server schedules.
$atlasEvents = [
    ['id'=>'pandora','name'=>'Pandora Event','category'=>'COMPETENCIA / PVP','line'=>'El continente tiene un objeto por disputar.','status'=>'Instalación V8 confirmada','intro'=>'Una disputa entre jugadores por el objeto del evento. Conseguirlo es solo el comienzo: defendé su posesión hasta el cierre.',
     'facts'=>['Cómo participar'=>'Seguí el anuncio y acudí al lugar indicado dentro del juego.','Tu objetivo'=>'Disputar el objeto y conservarlo hasta el cierre del evento.','Duración'=>'5 minutos de competencia.','Horarios'=>'19:15 y 22:15 · hora Argentina.'],
     'rewards'=>'2 Jewel of Bless · 2 Jewel of Soul · 1 Jewel of Chaos. Jewel of Life: 50% de posibilidad.','bags'=>[],
     'note'=>'Horarios y premios de la instalación V8 confirmada el 06/10. Arte conceptual; no es una captura del cliente.'],
    ['id'=>'blood-castle','name'=>'Blood Castle','category'=>'MISIÓN / COOPERACIÓN','line'=>'Abrí el camino. Recuperá el objetivo.','status'=>'Recompensas por categoría','intro'=>'Avanzá por el puente, abrí paso hacia la fortaleza y recuperá el arma del ángel. La misión termina al devolverla dentro del tiempo del evento.',
     'facts'=>['Cómo entrar'=>'Con una Invisibility Cloak de la categoría que te habilita el juego.','Tu objetivo'=>'Abrir el camino, recuperar el arma y entregarla al ángel.','Preparación'=>'Creá la entrada en Chaos. Revisá la categoría y sus requisitos en el cliente.','Horarios'=>'Pendientes de verificar con la configuración vigente.'],
     'rewards'=>null,'bags'=>range(12,19),'note'=>'Los objetos posibles dependen de la categoría y de las condiciones de recompensa. Arte conceptual.'],
    ['id'=>'devil-square','name'=>'Devil Square','category'=>'COMBATE / SUPERVIVENCIA','line'=>'Las oleadas no esperan. Tu party tampoco.','status'=>'Recompensas por categoría','intro'=>'Una arena con oleadas de monstruos. Prepará tu personaje, resistí el combate y sumá puntos derrotando criaturas durante el evento.',
     'facts'=>['Cómo entrar'=>"Con una Devil’s Invitation de la categoría habilitada por el juego.",'Tu objetivo'=>'Sobrevivir a las oleadas y sumar puntos durante el combate.','Preparación'=>'Creá la invitación en Chaos y llevá recursos para sostener las oleadas.','Horarios'=>'Pendientes de verificar con la configuración vigente.'],
     'rewards'=>null,'bags'=>range(145,151),'note'=>'La lista muestra posibilidades configuradas, no una entrega garantizada de todos los objetos. Arte conceptual.']
];
?>
<section id="eventos" class="wiki-section" aria-labelledby="atlas-events-title">
    <div class="atlas-section-heading"><div><span class="eyebrow">EL CONTINENTE NO SE DETIENE</span><h2 id="atlas-events-title">Respondé al desafío.</h2></div><span class="atlas-section-mark" aria-hidden="true">III</span></div>
    <p>Conocé el objetivo, prepará tu entrada y descubrí qué podés conseguir.</p>
    <div class="atlas-agenda"><div class="atlas-agenda-head"><h3>Agenda confirmada</h3><span>Hora Argentina<br>UTC−3</span></div><div class="atlas-agenda-entry"><span>Pandora Event · instalación V8</span><div><time>19:15</time><time>22:15</time></div></div><p class="atlas-agenda-note">Blood Castle y Devil Square: sus horarios se incorporarán después de verificar la configuración vigente del servidor.</p></div>
    <div class="atlas-event-grid"><?php foreach($atlasEvents as $event) { ?><article class="atlas-event-card"><img loading="lazy" width="640" height="360" src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/editorial/<?php echo $event['id']; ?>.webp" alt=""><div><span class="eyebrow"><?php echo $event['category']; ?></span><h3><?php echo $event['name']; ?></h3><p><?php echo $event['line']; ?></p><span class="atlas-event-status"><?php echo $event['status']; ?></span><a href="#evento-<?php echo $event['id']; ?>" data-atlas-event-open="<?php echo $event['id']; ?>">Conocer el evento →</a></div></article><?php } ?></div>
    <?php foreach($atlasEvents as $event) { $eventRewards=[]; foreach($wiki['eventBags'] ?? [] as $bag) { if(in_array($bag['id'],$event['bags'],true) && in_array($bag['format'],['standard','advanced'],true)) foreach($bag['items'] as $reward) $eventRewards[$reward['name']]=$reward['name']; } ?>
    <article id="evento-<?php echo $event['id']; ?>" class="atlas-event-full" data-atlas-event="<?php echo $event['id']; ?>">
        <div class="atlas-event-dossier"><div class="atlas-event-visual"><img loading="lazy" width="640" height="960" src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/editorial/<?php echo $event['id']; ?>.webp" alt=""><span aria-hidden="true"><?php echo $event['name']; ?></span></div><div class="atlas-event-copy"><span class="eyebrow"><?php echo $event['category']; ?></span><h3><?php echo $event['name']; ?></h3><p><?php echo $event['intro']; ?></p><dl class="atlas-event-facts"><?php foreach($event['facts'] as $label=>$value) { ?><div><dt><?php echo panicWikiEscape($label); ?></dt><dd><?php echo panicWikiEscape($value); ?></dd></div><?php } ?></dl><div class="atlas-event-rewards"><strong>Recompensas</strong><?php echo panicWikiEscape($event['rewards'] ?? ($eventRewards ? implode(' · ',$eventRewards) : 'Lista todavía pendiente de verificar.')); ?><?php if($event['bags']) { ?><div class="atlas-event-tiers" aria-label="Recompensas por categoría"><?php foreach($event['bags'] as $i=>$id) { ?><a href="#recompensa-<?php echo $id; ?>">Categoría <?php echo $i+1; ?> ↗</a><?php } ?></div><?php } ?></div><p class="atlas-event-footnote"><?php echo $event['note']; ?></p></div></div>
    </article>
    <?php } ?>
</section>
<dialog class="atlas-event-dialog" data-atlas-event-dialog aria-label="Detalles del evento"><button class="atlas-event-close" type="button" data-atlas-event-close aria-label="Cerrar evento">×</button><div data-atlas-event-content></div></dialog>
