<?php if(!defined('access') or !access) die(); ?>
<section id="inicio" class="wiki-section atlas-home" aria-labelledby="atlas-home-title">
    <div class="atlas-section-heading"><div><span class="eyebrow">TU PRÓXIMA AVENTURA</span><h2 id="atlas-home-title">Un mundo por conquistar.</h2></div><span class="atlas-section-mark" aria-hidden="true">I</span></div>
    <p>Elegí tu destino. Prepará tu equipo. Encontrá una nueva recompensa.</p>
    <div class="atlas-home-grid">
        <a class="atlas-home-card" href="#progresion"><div class="atlas-home-art"><img src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/maps/0.webp" alt="" width="640" height="360"></div><div><span class="atlas-purpose">01 / EL CONTINENTE</span><h3>Mapas y territorios</h3><p>Explorá cada zona, sus spots y las criaturas que la habitan.</p><strong>Elegir mi destino <span>→</span></strong></div></a>
        <a class="atlas-home-card atlas-home-boss" href="#recompensas"><div class="atlas-home-art atlas-home-creatures"><?php if(isset($atlasAssets['monsters']['561'])) { ?><img src="<?php echo __PATH_TEMPLATE__.panicWikiEscape($atlasAssets['monsters']['561']['file']); ?>" alt="" width="360" height="360"><?php } ?></div><div><span class="atlas-purpose">02 / LA CONQUISTA</span><h3>Bosses y recompensas</h3><p>Conocé tus objetivos y descubrí qué pueden dejar.</p><strong>Consultar recompensas <span>→</span></strong></div></a>
        <a class="atlas-home-card" href="#eventos"><div class="atlas-home-art"><img src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/editorial/blood-castle.webp" alt="" width="640" height="360"></div><div><span class="atlas-purpose">03 / EL DESAFÍO</span><h3>Eventos del continente</h3><p>Cómo participar, qué buscar y cuándo prepararte.</p><strong>Explorar eventos <span>→</span></strong></div></a>
        <a class="atlas-home-card" href="#buscar"><div class="atlas-home-art"><img src="<?php echo __PATH_TEMPLATE__; ?>img/server/systems/vault-47074095857a.webp" alt="" width="640" height="360"></div><div><span class="atlas-purpose">04 / TU EQUIPO</span><h3>Encontrá lo que buscás</h3><p>Objetos, monstruos y las rutas para conseguirlos.</p><strong>Buscar mi objetivo <span>→</span></strong></div></a>
    </div>
    <div class="atlas-home-trail"><span class="atlas-trail-icon" aria-hidden="true"><?php echo mupanicGlyph('wings'); ?></span><div><span class="eyebrow">CADA HÉROE TIENE UN COMIENZO</span><h3>Tu camino empieza acá.</h3><p>Primeros pasos, progresión y recetas para preparar tu personaje.</p></div><a href="#primeros-pasos">Abrir la guía →</a></div>
    <div class="atlas-basics"><dl><div><dt>Spot</dt><dd>Una zona con monstruos que reaparecen para entrenar.</dd></div><div><dt>Drop</dt><dd>Un objeto que puede dejar una criatura al derrotarla.</dd></div><div><dt>Recompensa</dt><dd>Una selección de premios con condiciones propias.</dd></div></dl></div>
</section>
