<?php if(!defined('access') or !access) die(); ?>
<section id="inicio" class="wiki-section atlas-home" aria-labelledby="atlas-home-title">
    <div class="atlas-section-heading"><div><span class="eyebrow">TU PRÓXIMA AVENTURA</span><h2 id="atlas-home-title">Un mundo por conquistar.</h2></div><span class="atlas-section-mark" aria-hidden="true">I</span></div>
    <p>Elegí tu destino. Prepará tu equipo. Encontrá una nueva recompensa.</p>
    <div class="atlas-home-grid">
        <a class="atlas-home-card" href="#progresion"><div class="atlas-home-art"><img src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/editorial/atlas-territories.webp" alt="" width="640" height="360"></div><div><span class="atlas-purpose">01 / EL CONTINENTE</span><h3>Mapas y territorios</h3><p>Explorá cada zona, sus spots y las criaturas que la habitan.</p><strong>Elegir mi destino <span>→</span></strong></div></a>
        <a class="atlas-home-card atlas-home-boss" href="#recompensas"><div class="atlas-home-art"><img src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/editorial/atlas-medusa.webp" alt="" width="1536" height="1024"></div><div><span class="atlas-purpose">02 / LA CONQUISTA</span><h3>Bosses y recompensas</h3><p>Conocé tus objetivos y descubrí qué pueden dejar.</p><strong>Consultar recompensas <span>→</span></strong></div></a>
        <a class="atlas-home-card" href="#eventos"><div class="atlas-home-art"><img src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/editorial/blood-castle.webp" alt="" width="640" height="360"></div><div><span class="atlas-purpose">03 / EL DESAFÍO</span><h3>Eventos del continente</h3><p>Cómo participar, qué buscar y cuándo prepararte.</p><strong>Explorar eventos <span>→</span></strong></div></a>
        <a class="atlas-home-card" href="#buscar"><div class="atlas-home-art"><img src="<?php echo __PATH_TEMPLATE__; ?>img/server/systems/vault-47074095857a.webp" alt="" width="640" height="360"></div><div><span class="atlas-purpose">04 / TU EQUIPO</span><h3>Encontrá lo que buscás</h3><p>Objetos, monstruos y las rutas para conseguirlos.</p><strong>Buscar mi objetivo <span>→</span></strong></div></a>
    </div>
    <a class="vinculos-home" href="#vinculos"><img src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/vinculos/vaeraxes-cinematic.webp" alt="" width="384" height="384"><div><span class="eyebrow">EL PACTO DE LOS OCHO Y SUS NUEVAS LEYENDAS</span><h3>Vínculos de PANIC.</h3><p>Historias, evoluciones, mascotas exclusivas y monturas. Descubrí a tu próximo compañero.</p><strong>Explorar los vínculos →</strong></div></a>
    <div class="atlas-home-trail"><span class="atlas-trail-icon" aria-hidden="true"><?php echo mupanicGlyph('wings'); ?></span><div><span class="eyebrow">CADA HÉROE TIENE UN COMIENZO</span><h3>Tu camino empieza acá.</h3><p>Primeros pasos, progresión y recetas para preparar tu personaje.</p></div><a href="#primeros-pasos">Abrir la guía →</a></div>
</section>
