<?php
if(!defined('access') || !access) die();
$vinculos = $wiki['vinculos'];
$bySlug = []; foreach($vinculos['entries'] as $companion) $bySlug[$companion['slug']] = $companion;
$esc = 'panicWikiEscape';
$renderCompanion = function($pet) use ($esc) {
?>
<details class="vinculo-card vinculo-card--<?php echo $esc($pet['kind']); ?>" id="vinculo-<?php echo $esc($pet['slug']); ?>" data-vinculo>
    <summary>
        <div class="vinculo-portrait"><img src="<?php echo __PATH_TEMPLATE__.$esc($pet['image']); ?>" alt="<?php echo $esc($pet['name']); ?>" loading="lazy" decoding="async" width="640" height="640"><span><?php echo $pet['stage'] ? 'ETAPA '.$pet['stage'].' / '.$pet['stages'] : ($pet['kind']==='montura' ? 'MONTURA EXCLUSIVA' : ($pet['kind']==='exclusiva' ? 'MASCOTA EXCLUSIVA' : 'EL COMPAÑERO INESPERADO')); ?></span></div>
        <div class="vinculo-heading"><h4><?php echo $esc($pet['name']); ?></h4><p><?php echo $esc($pet['title']); ?></p><ul><?php foreach($pet['stats'] as $stat) { ?><li><?php echo $esc($stat); ?></li><?php } ?></ul><span class="vinculo-open">Conocé su historia y cómo conseguirlo <b aria-hidden="true">+</b></span></div>
    </summary>
    <div class="vinculo-story">
        <?php if($pet['quote']) { ?><blockquote>«<?php echo $esc($pet['quote']); ?>»</blockquote><?php } ?>
        <?php if($pet['chapter']) { ?><span class="eyebrow"><?php echo $esc($pet['chapter']); ?></span><?php } ?>
        <?php foreach($pet['story'] as $paragraph) { ?><p><?php echo $esc($paragraph); ?></p><?php } ?>
        <?php if($pet['role']) { ?><div class="vinculo-role"><strong>Su lugar en MU PANIC</strong><p><?php echo $esc($pet['role']); ?></p></div><?php } ?>
        <dl class="vinculo-facts"><div><dt>Cómo conseguirlo</dt><dd><?php echo $esc($pet['obtain']); ?></dd></div><div><dt>Espacio en inventario</dt><dd><?php echo $esc($pet['inventory']); ?></dd></div></dl>
        <?php if($pet['kind']==='pacto') { ?><a href="#vinculo-eryndor">Ver invocación y evoluciones →</a><?php } else { ?><p class="vinculo-sale">Exclusivo de la tienda. No forma parte del drop, la invocación ni las evoluciones con Eryndor.</p><?php } ?>
    </div>
</details>
<?php }; ?>
<section id="vinculos" class="wiki-section atlas-vinculos" aria-labelledby="vinculos-title">
    <header class="vinculos-hero"><div><span class="eyebrow">COMPAÑEROS / LINAJES / LEYENDAS</span><h2 id="vinculos-title">Vínculos<br>de <em>PANIC.</em></h2><p>Algunos vínculos nacen de un pacto. Otros llegan desde el eclipse, las profundidades o los últimos reinos. Descubrí quién va a acompañar tu próxima batalla.</p></div><div class="vinculos-hero-art" aria-hidden="true"><img src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/vinculos/vaerion.webp" alt="" width="384" height="384"><img src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/vinculos/elyndra.webp" alt="" width="384" height="384"><img src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/vinculos/aurion.webp" alt="" width="640" height="640"></div></header>
    <nav class="vinculos-chapters" aria-label="Capítulos de Vínculos de PANIC"><a href="#vinculo-pacto">El Pacto de los Ocho</a><a href="#vinculo-eryndor">Invocar y evolucionar</a><a href="#vinculo-materiales">Materiales</a><a href="#vinculo-exclusivas">Vínculos exclusivos</a><a href="#vinculo-monturas">Monturas legendarias</a></nav>
    <article class="vinculos-prologue" id="vinculo-pacto"><span class="eyebrow">CRÓNICAS DEL VÍNCULO / LA FRACTURA</span><h3>El Pacto de los Ocho.</h3><p class="vinculos-lead">Ocho compañeros. Tres linajes.<br>Un mundo que todavía puede salvarse.</p><h4>Cuando el mundo perdió su vínculo</h4><?php foreach($vinculos['prologue'] as $paragraph) { ?><p><?php echo $esc($paragraph); ?></p><?php } ?><div class="vinculos-lineages"><?php foreach($vinculos['families'] as $family) { ?><a href="#vinculo-linaje-<?php echo $esc($family['id']); ?>"><span><?php echo $esc($family['theme']); ?></span><strong><?php echo $esc($family['name']); ?></strong><p><?php echo $esc($family['intro']); ?></p></a><?php } ?></div></article>
    <?php foreach($vinculos['families'] as $family) { ?>
    <div class="vinculos-family" id="vinculo-linaje-<?php echo $esc($family['id']); ?>"><span class="eyebrow"><?php echo $esc($family['theme']); ?></span><h3><?php echo $esc($family['name']); ?></h3><p><?php echo $esc($family['intro']); ?></p><nav class="vinculos-evolution" aria-label="Evoluciones de <?php echo $esc($family['name']); ?>"><?php foreach($family['path'] as $i=>$slug) { if($i) { ?><span aria-hidden="true">→</span><?php } ?><a href="#vinculo-<?php echo $esc($slug); ?>"><?php echo $esc($bySlug[$slug]['name']); ?></a><?php } ?></nav><div class="vinculos-grid"><?php foreach($family['path'] as $slug) $renderCompanion($bySlug[$slug]); ?></div></div>
    <?php } ?>
    <div class="vinculos-grum"><?php $renderCompanion($bySlug['grum']); ?><div><span class="eyebrow">EL RESULTADO INESPERADO</span><h3>También puede aparecer Grum.</h3><p>Recoge Zen, pero no agrega bonos de combate ni de experiencia. Tiene un 10% dentro del reparto de invocaciones exitosas.</p><p>Podés canjear tres Grum con Eryndor por una mascota inicial al azar: Aelira, Aurik o Vaeryn, con la misma posibilidad para cada familia.</p></div></div>
    <article class="vinculos-ritual" id="vinculo-eryndor"><span class="eyebrow">ERYNDOR / EL CUSTODIO DEL VÍNCULO</span><h3>Tu pacto empieza en Lorencia.</h3><p>Buscá a Eryndor en <strong>X 130 / Y 140</strong>. Reuní los materiales, dejá espacio libre para tu mascota y elegí el vínculo que querés formar.</p><div class="vinculos-ritual-grid"><div><span>01 / INVOCACIÓN</span><h4>Un compañero al azar.</h4><p><a href="#vinculo-fragmentos">10 Fragmentos de Vínculo</a><br><strong>20.000.000 de Zen · 50% de éxito</strong></p><p>Si la invocación sale bien: 30% Aelira, 30% Aurik, 30% Vaeryn y 10% Grum. Por intento completo equivale a 15%, 15%, 15%, 5% y 50% de fallo.</p></div><div><span>02 / SEGUNDA ETAPA</span><h4>Hacé crecer tu vínculo.</h4><p><a href="#vinculo-nucleos">10 Núcleos de Evolución</a><br><strong>50.000.000 de Zen · 60% de éxito</strong></p><p>Aelira → Sylthara, Aurik → Aurion o Vaeryn → Vaerath. Si falla, conservás la mascota base; los materiales y el Zen se consumen.</p></div><div><span>03 / EVOLUCIÓN FINAL</span><h4>Despertá su leyenda.</h4><p><a href="#vinculo-nucleos">20 Núcleos de Evolución</a><br><strong>100.000.000 de Zen · 30% de éxito</strong></p><p>Sylthara → Elyndra o Vaerath → Vaerion. Si falla, perdés la mascota base salvo que agregues <a href="#vinculo-assembly">Chaos Assembly</a>. Los materiales y el Zen se consumen.</p></div></div><p>Podés sumar <a href="#vinculo-luck">Talisman of Luck</a> a las evoluciones: +1 punto porcentual por talismán, hasta 10. La protección de Chaos Assembly se consume y no aumenta el éxito.</p></article>
    <div class="vinculos-materials" id="vinculo-materiales"><span class="eyebrow">CADA RECURSO TIENE UN DESTINO</span><h3>Los materiales del vínculo.</h3><div class="vinculos-grid vinculos-grid--materials"><?php foreach($vinculos['materials'] as $material) { ?><article class="vinculo-material" id="vinculo-<?php echo $esc($material['slug']); ?>"><div class="vinculo-material-art"><?php if($material['image']) { ?><img src="<?php echo __PATH_TEMPLATE__.$esc($material['image']); ?>" alt="<?php echo $esc($material['name']); ?>" loading="lazy" width="384" height="384"><?php } else { ?><span class="vinculo-material-symbol" aria-hidden="true"><?php echo mupanicGlyph($material['slug']==='luck' ? 'gem' : 'crest'); ?></span><?php } ?></div><span class="eyebrow"><?php echo $esc($material['title']); ?></span><h4><?php echo $esc($material['name']); ?></h4><p><?php echo $esc($material['use']); ?></p><p><?php echo $esc($material['detail']); ?></p><p class="vinculo-source"><?php echo $esc($material['obtain']); ?></p>
<?php $materialRules = []; foreach($wiki['drops'] as $index=>$rule) if($rule['id'] === $material['id']) $materialRules[$index]=$rule;
if($materialRules) { ?><details class="vinculo-drop-rules"><summary>Dónde conseguirlo · <?php echo count($materialRules); ?> reglas de drop</summary><ul><?php foreach($materialRules as $index=>$rule) { ?><li><a href="#drop-<?php echo $index; ?>"><?php echo $esc($mapNames[$rule['map']] ?? ($rule['map'] === -1 ? 'Drop general' : 'Mapa '.$rule['map'])); ?></a><span><?php echo panicWikiRate($rule['rates'][0]); ?></span></li><?php } ?></ul><small>Tasas de las reglas publicadas, no una probabilidad final garantizada por muerte. Abrí el mapa para consultar sus condiciones.</small></details><?php } ?></article><?php } ?></div></div>
    <div class="vinculos-family" id="vinculo-exclusivas"><span class="eyebrow">EL ECLIPSE Y EL EQUILIBRIO</span><h3>Dos vínculos exclusivos.</h3><p>Vaelkar y Aurethia tienen los mismos poderes y una apariencia distinta. Su obtención será por venta directa en la tienda, sin azar.</p><div class="vinculos-grid"><?php foreach($vinculos['entries'] as $pet) if($pet['kind']==='exclusiva') $renderCompanion($pet); ?></div></div>
    <div class="vinculos-family" id="vinculo-monturas"><span class="eyebrow">MARFIL / ABISMO / CARMESÍ</span><h3>Monturas legendarias.</h3><p>Tres formas de recorrer MU PANIC: avanzar, resistir o llevar el combate al siguiente nivel. Cada montura ocupa cuatro casillas de inventario.</p><div class="vinculos-grid"><?php foreach($vinculos['entries'] as $pet) if($pet['kind']==='montura') $renderCompanion($pet); ?></div><p class="wiki-note">Los bonos de las monturas se están probando en beta y pueden ajustarse antes del lanzamiento. La acumulación con otros bonos sigue en evaluación.</p></div>
</section>
