<?php
if(!defined('access') || !access) die();
$vinculos = $wiki['vinculos'];
$bySlug = []; foreach($vinculos['entries'] as $companion) $bySlug[$companion['slug']] = $companion;
$esc = 'panicWikiEscape';
$renderCompanion = function($pet) use ($esc) {
?>
<details class="vinculo-card vinculo-card--<?php echo $esc($pet['kind']); ?>" id="vinculo-<?php echo $esc($pet['slug']); ?>" data-vinculo data-vinculo-kind="<?php echo $esc($pet['kind']); ?>">
    <summary>
        <div class="vinculo-portrait"><i class="vinculo-aura" aria-hidden="true"></i><img src="<?php echo __PATH_TEMPLATE__.$esc($pet['image']); ?>" alt="<?php echo $esc($pet['name']); ?>" loading="lazy" decoding="async" width="640" height="640"><span><?php echo $pet['stage'] ? 'ETAPA '.$pet['stage'].' / '.$pet['stages'] : ($pet['kind']==='montura' ? 'MONTURA EXCLUSIVA' : ($pet['kind']==='exclusiva' ? 'MASCOTA EXCLUSIVA' : 'EL COMPAÑERO INESPERADO')); ?></span></div>
        <div class="vinculo-heading"><h4><?php echo $esc($pet['name']); ?></h4><p><?php echo $esc($pet['title']); ?></p><ul><?php foreach($pet['stats'] as $stat) { if($pet['kind']!=='pacto') { $value='AUTO'; $label=$stat; if(preg_match('/[+−]?\d+(?:%| puntos)?/u', $stat, $number)) { $value=$number[0]; $label=trim(str_replace($value, '', $stat)); } ?><li class="vinculo-power"><strong><?php echo $esc($value); ?></strong><span><?php echo $esc($label); ?></span></li><?php } else { ?><li><?php echo $esc($stat); ?></li><?php } } ?></ul><span class="vinculo-open">Historia, poderes y obtención <b class="vinculo-toggle" aria-hidden="true"></b></span></div>
    </summary>
    <div class="vinculo-story">
        <?php if($pet['quote']) { ?><blockquote>«<?php echo $esc($pet['quote']); ?>»</blockquote><?php } ?>
        <?php if($pet['chapter']) { ?><span class="eyebrow"><?php echo $esc($pet['chapter']); ?></span><?php } ?>
        <?php foreach($pet['story'] as $paragraph) { ?><p><?php echo $esc($paragraph); ?></p><?php } ?>
        <?php if($pet['role']) { ?><div class="vinculo-role"><strong>Su lugar en MU PANIC</strong><p><?php echo $esc($pet['role']); ?></p></div><?php } ?>
        <dl class="vinculo-facts"><div><dt>Cómo conseguirlo</dt><dd><?php echo $esc($pet['obtain']); ?></dd></div></dl>
        <?php if($pet['kind']==='pacto') { ?><a href="#vinculo-eryndor">Ver invocación y evoluciones →</a><?php } else { ?><p class="vinculo-sale">Exclusivo de la tienda. No forma parte del drop, la invocación ni las evoluciones con Eryndor.</p><?php } ?>
    </div>
</details>
<?php }; ?>
<section id="vinculos" class="wiki-section atlas-vinculos atlas-vinculos--cinematic" aria-labelledby="vinculos-title">
    <header class="vinculos-hero">
        <div class="vinculos-hero-copy"><span class="eyebrow">MU PANIC / EL BESTIARIO DEL VÍNCULO</span><h2 id="vinculos-title">Ninguna leyenda<br>se escribe <em>solo.</em></h2><p>Vínculos que evolucionan. Guardianes del eclipse. Monturas que cambian tu forma de entrar en batalla.</p><div class="vinculos-hero-actions"><a class="vinculos-action" href="#vinculo-pacto">Conocé el Pacto de los Ocho <span aria-hidden="true">↗</span></a><a href="#vinculo-exclusivas">Los Custodios del Eclipse <span aria-hidden="true">→</span></a></div><div class="vinculos-hero-signature"><span>VÍNCULOS DE PANIC</span><span>HISTORIAS QUE SE JUEGAN.</span></div></div>
        <div class="vinculos-hero-art vinculos-hero-art--pact" aria-hidden="true"><?php foreach(["aurion","vaerion","elyndra"] as $slug) { ?><img class="vinculos-hero-member vinculos-hero-member--<?php echo $slug; ?>" src="<?php echo __PATH_TEMPLATE__.$esc($bySlug[$slug]["image"]); ?>" alt="" width="1024" height="1024" decoding="async"><?php } ?><div class="vinculos-hero-creature"><span>VIDA / MEMORIA / PODER</span><strong>El Pacto de los Ocho</strong><small>Tres linajes. Una promesa que sobrevive.</small></div></div>
    </header>
    <nav class="vinculos-chapters" aria-label="Capítulos de Vínculos de PANIC">
        <a href="#vinculo-pacto" class="vinculos-chapter vinculos-chapter--pact"><span class="vinculos-chapter-number">01</span><img src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/vinculos/aurion-cinematic.webp" alt="" width="640" height="640"><div><small>VIDA / MEMORIA / PODER</small><strong>El Pacto de los Ocho</strong><span>Un compañero que crece con vos. <b aria-hidden="true">↗</b></span></div></a>
        <a href="#vinculo-exclusivas" class="vinculos-chapter vinculos-chapter--eclipse"><span class="vinculos-chapter-number">02</span><img src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/vinculos/vaelkar-cinematic.webp" alt="" width="1024" height="1024"><div><small>EL ECLIPSE Y EL EQUILIBRIO</small><strong>Los exclusivos</strong><span>Dos presencias. El mismo poder. <b aria-hidden="true">↗</b></span></div></a>
        <a href="#vinculo-monturas" class="vinculos-chapter vinculos-chapter--mounts"><span class="vinculos-chapter-number">03</span><img src="<?php echo __PATH_TEMPLATE__; ?>img/atlas/vinculos/theryon-cinematic.webp" alt="" width="1024" height="1024"><div><small>MARFIL / ABISMO / CARMESÍ</small><strong>Monturas legendarias</strong><span>Elegí cómo entrar en batalla. <b aria-hidden="true">↗</b></span></div></a>
        <div class="vinculos-chapter-tools"><a href="#vinculo-eryndor">El ritual de evolución <span aria-hidden="true">→</span></a><a href="#vinculo-materiales">Materiales y talismanes <span aria-hidden="true">→</span></a></div>
    </nav>
    <section class="vinculos-pact" id="vinculo-pacto" aria-labelledby="vinculos-pact-title">
        <header class="vinculos-section-heading"><span class="vinculos-section-index" aria-hidden="true">01</span><div><span class="eyebrow">CRÓNICAS DEL VÍNCULO / LA FRACTURA</span><h3 id="vinculos-pact-title">El Pacto<br><em>de los Ocho.</em></h3><p>Ocho compañeros. Tres linajes. Un mundo que todavía puede salvarse.</p></div></header>
        <article class="vinculos-chronicle vinculos-chronicle--pact" aria-labelledby="vinculos-fractura-title"><header><span class="eyebrow">EL ORIGEN / LA FRACTURA</span><h4 id="vinculos-fractura-title">Cuando el mundo<br>perdió su vínculo.</h4><p class="vinculos-chronicle-motto">La vida. La memoria. El poder.<br>Tres fuerzas que debían volver a encontrarse.</p></header><div class="vinculos-prologue-acts"><?php $acts=[['I','La noche del quiebre'],['II','Un continente separado'],['III','La promesa de los Ocho']]; foreach($vinculos['prologue'] as $i=>$paragraph) { ?><div><span><?php echo $acts[$i][0]; ?></span><h5><?php echo $acts[$i][1]; ?></h5><p><?php echo $esc($paragraph); ?></p></div><?php } ?></div><div class="vinculos-pact-seal"><span>08 COMPAÑEROS</span><span>03 LINAJES</span><span>01 PACTO</span></div></article>
        <nav class="vinculos-lineages" aria-label="Los tres linajes"><?php foreach($vinculos['families'] as $family) { $leader=$bySlug[end($family['path'])]; ?><a class="vinculos-lineage--<?php echo $esc($family['id']); ?>" href="#vinculo-linaje-<?php echo $esc($family['id']); ?>"><img src="<?php echo __PATH_TEMPLATE__.$esc($leader['image']); ?>" alt="" loading="lazy" width="640" height="640"><div><span><?php echo $esc($family['theme']); ?></span><strong><?php echo $esc($family['name']); ?></strong><p><?php echo $esc($family['intro']); ?></p></div></a><?php } ?></nav>
        <?php foreach($vinculos['families'] as $family) { ?>
        <section class="vinculos-family vinculos-family--<?php echo $esc($family['id']); ?>" id="vinculo-linaje-<?php echo $esc($family['id']); ?>">
            <header class="vinculos-family-heading"><span class="vinculos-family-sigil" aria-hidden="true"><?php echo mupanicGlyph($family['id']==='vida' ? 'crest' : 'gem'); ?></span><div><span class="eyebrow"><?php echo $esc($family['theme']); ?></span><h3><?php echo $esc($family['name']); ?></h3><p><?php echo $esc($family['intro']); ?></p></div></header>
            <nav class="vinculos-evolution" aria-label="Evoluciones de <?php echo $esc($family['name']); ?>"><?php foreach($family['path'] as $i=>$slug) { if($i) { ?><span aria-hidden="true">→</span><?php } ?><a href="#vinculo-<?php echo $esc($slug); ?>"><small>ETAPA <?php echo $i+1; ?></small><strong><?php echo $esc($bySlug[$slug]['name']); ?></strong></a><?php } ?></nav>
            <div class="vinculos-grid vinculos-grid--pact"><?php foreach($family['path'] as $slug) $renderCompanion($bySlug[$slug]); ?></div>
        </section><?php } ?>
    <div class="vinculos-grum"><?php $renderCompanion($bySlug['grum']); ?><div><span class="eyebrow">EL RESULTADO INESPERADO</span><h3>También puede aparecer Grum.</h3><p>Recoge Zen, pero no agrega bonos de combate ni de experiencia. Tiene un 10% dentro del reparto de invocaciones exitosas.</p><p>Podés canjear tres Grum con Eryndor por una mascota inicial al azar: Aelira, Aurik o Vaeryn, con la misma posibilidad para cada familia.</p></div></div>
    </section>
    <section class="vinculos-showcase vinculos-showcase--exclusive" id="vinculo-exclusivas" aria-labelledby="vinculos-exclusive-title">
        <header class="vinculos-section-heading"><span class="vinculos-section-index" aria-hidden="true">02</span><div><span class="eyebrow">EL ECLIPSE Y EL EQUILIBRIO</span><h3 id="vinculos-exclusive-title">Los Custodios<br><em>del Eclipse.</em></h3><p>Vaelkar y Aurethia. Los mismos poderes, dos formas de dejar tu huella. Venta directa en la tienda, sin azar.</p></div></header>
        <div class="vinculos-store-strip"><span>VÍNCULOS EXCLUSIVOS DE PANIC</span><strong>La tienda abre próximamente.</strong></div>
        <article class="vinculos-chronicle vinculos-chronicle--exclusive" aria-labelledby="vinculos-exclusive-lore-title"><div class="vinculos-legend-art" aria-hidden="true"><?php foreach(['vaelkar','aurethia'] as $slug) { ?><img src="<?php echo __PATH_TEMPLATE__.$esc($bySlug[$slug]['image']); ?>" alt="" loading="lazy" width="1024" height="1024"><?php } ?></div><div class="vinculos-legend-copy"><span class="eyebrow"><?php echo $esc($vinculos['chronicles']['exclusive']['eyebrow']); ?></span><h4 id="vinculos-exclusive-lore-title"><?php echo $esc($vinculos['chronicles']['exclusive']['title']); ?></h4><blockquote>«<?php echo $esc($vinculos['chronicles']['exclusive']['quote']); ?>»</blockquote><?php foreach($vinculos['chronicles']['exclusive']['paragraphs'] as $paragraph) { ?><p><?php echo $esc($paragraph); ?></p><?php } ?></div></article>
        <div class="vinculos-grid vinculos-grid--exclusive"><?php foreach($vinculos['entries'] as $pet) if($pet['kind']==='exclusiva') $renderCompanion($pet); ?></div>
    </section>
    <section class="vinculos-showcase vinculos-showcase--mounts" id="vinculo-monturas" aria-labelledby="vinculos-mounts-title">
        <header class="vinculos-section-heading"><span class="vinculos-section-index" aria-hidden="true">03</span><div><span class="eyebrow">MARFIL / ABISMO / CARMESÍ</span><h3 id="vinculos-mounts-title">Las Tres Bestias<br><em>Primordiales.</em></h3><p>Avanzar, resistir o llevar el combate al siguiente nivel. Tres bestias primordiales, tres leyendas que siguen escribiéndose.</p></div></header>
        <article class="vinculos-chronicle vinculos-chronicle--mounts" aria-labelledby="vinculos-mounts-lore-title"><div class="vinculos-legend-art" aria-hidden="true"><?php foreach(['theryon','nerathys','vaeraxes'] as $slug) { ?><img src="<?php echo __PATH_TEMPLATE__.$esc($bySlug[$slug]['image']); ?>" alt="" loading="lazy" width="1024" height="1024"><?php } ?></div><div class="vinculos-legend-copy"><span class="eyebrow"><?php echo $esc($vinculos['chronicles']['mounts']['eyebrow']); ?></span><h4 id="vinculos-mounts-lore-title"><?php echo $esc($vinculos['chronicles']['mounts']['title']); ?></h4><blockquote>«<?php echo $esc($vinculos['chronicles']['mounts']['quote']); ?>»</blockquote><?php foreach($vinculos['chronicles']['mounts']['paragraphs'] as $paragraph) { ?><p><?php echo $esc($paragraph); ?></p><?php } ?></div></article>
        <div class="vinculos-grid vinculos-grid--mounts"><?php foreach($vinculos['entries'] as $pet) if($pet['kind']==='montura') $renderCompanion($pet); ?></div>
        <p class="wiki-note">Los bonos de las monturas se están probando en beta y pueden ajustarse antes del lanzamiento. La acumulación con otros bonos sigue en evaluación.</p>
    </section>
    <article class="vinculos-ritual" id="vinculo-eryndor"><div class="vinculos-ritual-intro"><span class="eyebrow">04 / ERYNDOR · EL CUSTODIO DEL VÍNCULO</span><h3>De un fragmento<br>a una <em>leyenda.</em></h3><p>Buscá a Eryndor en <strong>X 130 / Y 140</strong>. Reuní los materiales y elegí el vínculo que querés formar.</p></div><div class="vinculos-ritual-grid"><div><span>01 / INVOCACIÓN</span><h4>Un compañero al azar.</h4><p><a href="#vinculo-fragmentos">10 Fragmentos de Vínculo</a><br><strong>20.000.000 de Zen · 50% de éxito</strong></p><p>Si la invocación sale bien: 30% Aelira, 30% Aurik, 30% Vaeryn y 10% Grum. Por intento completo equivale a 15%, 15%, 15%, 5% y 50% de fallo.</p></div><div><span>02 / SEGUNDA ETAPA</span><h4>Hacé crecer tu vínculo.</h4><p><a href="#vinculo-nucleos">10 Núcleos de Evolución</a><br><strong>50.000.000 de Zen · 60% de éxito</strong></p><p>Aelira → Sylthara, Aurik → Aurion o Vaeryn → Vaerath. Si falla, conservás la mascota base; los materiales y el Zen se consumen.</p></div><div><span>03 / EVOLUCIÓN FINAL</span><h4>Despertá su leyenda.</h4><p><a href="#vinculo-nucleos">20 Núcleos de Evolución</a><br><strong>100.000.000 de Zen · 30% de éxito</strong></p><p>Sylthara → Elyndra o Vaerath → Vaerion. Si falla, perdés la mascota base salvo que agregues <a href="#vinculo-assembly">Chaos Assembly</a>. Los materiales y el Zen se consumen.</p></div></div><p>Podés sumar <a href="#vinculo-luck">Talisman of Luck</a> a las evoluciones: +1 punto porcentual por talismán, hasta 10. La protección de Chaos Assembly se consume y no aumenta el éxito.</p></article>
    <div class="vinculos-materials" id="vinculo-materiales"><header class="vinculos-section-heading"><span class="vinculos-section-index" aria-hidden="true">05</span><div><span class="eyebrow">CADA RECURSO TIENE UN DESTINO</span><h3>La materia<br>de las <em>leyendas.</em></h3><p>Reuní, invocá, evolucioná. Conocé lo que necesitás y dónde encontrarlo.</p></div></header><div class="vinculos-grid vinculos-grid--materials"><?php foreach($vinculos['materials'] as $material) { ?><article class="vinculo-material" id="vinculo-<?php echo $esc($material['slug']); ?>"><div class="vinculo-material-art"><?php if($material['image']) { ?><img src="<?php echo __PATH_TEMPLATE__.$esc($material['image']); ?>" alt="<?php echo $esc($material['name']); ?>" loading="lazy" width="384" height="384"><?php } else { ?><span class="vinculo-material-symbol" aria-hidden="true"><?php echo mupanicGlyph($material['slug']==='luck' ? 'gem' : 'crest'); ?></span><?php } ?></div><span class="eyebrow"><?php echo $esc($material['title']); ?></span><h4><?php echo $esc($material['name']); ?></h4><p><?php echo $esc($material['use']); ?></p><p><?php echo $esc($material['detail']); ?></p><p class="vinculo-source"><?php echo $esc($material['obtain']); ?></p>
<?php $materialRules = []; foreach($wiki['drops'] as $index=>$rule) if($rule['id'] === $material['id']) $materialRules[$index]=$rule;
if($materialRules) { ?><details class="vinculo-drop-rules"><summary>Dónde conseguirlo · <?php echo count($materialRules); ?> reglas de drop</summary><ul><?php foreach($materialRules as $index=>$rule) { ?><li><a href="#drop-<?php echo $index; ?>"><?php echo $esc($mapNames[$rule['map']] ?? ($rule['map'] === -1 ? 'Drop general' : 'Mapa '.$rule['map'])); ?></a><span><?php echo panicWikiRate($rule['rates'][0]); ?></span></li><?php } ?></ul><small>Tasas de las reglas publicadas, no una probabilidad final garantizada por muerte. Abrí el mapa para consultar sus condiciones.</small></details><?php } ?></article><?php } ?></div></div>
    <footer class="vinculos-finale"><span class="eyebrow">TU PRÓXIMO CAPÍTULO</span><h3>El vínculo es tuyo.<br><em>La leyenda, también.</em></h3><a class="vinculos-action" href="#vinculo-eryndor">Comenzá en Lorencia <span aria-hidden="true">→</span></a></footer>
</section>
