<?php if(!defined('access') or !access) die(); ?>
<div class="server-guide">
    <p class="guide-lead">Tu primera ruta por MU PANIC. Prepará tu cuenta, conocé las etapas y elegí tu próximo objetivo.</p>
    <nav class="guide-index" aria-label="Secciones de la guía"><a href="#primeros-pasos">Primeros pasos ↓</a><a href="#progresion">Ruta de mapas ↓</a><a href="#sistemas">Sistemas ↓</a></nav>
    <section id="primeros-pasos"><span class="eyebrow">01 / ANTES DE ENTRAR</span><h2>Prepará tu aventura.</h2><ol class="guide-steps"><li><strong>Creá tu cuenta.</strong><p>Registrá tu usuario y conservá tus datos de acceso. Si ya tenés cuenta, ingresá desde el menú superior.</p><a href="<?php echo __BASE_URL__; ?><?php echo $isLogged ? 'usercp/' : 'register/'; ?>"><?php echo $isLogged ? 'Ir a mi cuenta' : 'Crear cuenta'; ?> →</a></li><li><strong>Descargá el cliente de MU PANIC.</strong><p>Usá el cliente publicado en la sección Descargas. Los clientes de otros servidores pueden tener archivos distintos.</p><a href="<?php echo __BASE_URL__; ?>downloads/">Ver descargas →</a></li><li><strong>Elegí tu personaje y conocé sus habilidades.</strong><p>Empezá por las zonas iniciales. Probá el daño que recibís y que hacés antes de buscar un spot más exigente.</p></li></ol></section>
    <section id="progresion"><span class="eyebrow">02 / EL CONTINENTE</span><h2>Una ruta para orientarte.</h2><p>La siguiente tabla organiza el recorrido por etapas. No es una tabla de niveles mínimos: el equipo y tu personaje también determinan cuándo avanzar.</p><div class="guide-table-wrap"><table class="table"><thead><tr><th>Etapa</th><th>Mapas</th><th>En qué concentrarte</th></tr></thead><tbody><tr><td>Inicio</td><td>Lorencia / Noria / Elbeland</td><td>Primer equipo, habilidades y spots iniciales.</td></tr><tr><td>Transición</td><td>Devias / Dungeon</td><td>Revisá supervivencia y daño. Juntá Zen para tus próximas mejoras.</td></tr><tr><td>Farmeo</td><td>Atlans / Lost Tower</td><td>Buscá un spot sostenible y prepará equipo para el siguiente salto.</td></tr><tr><td>Ascenso</td><td>Tarkan / Icarus / Aida</td><td>Mejorá tu daño y prepará tus alas. Icarus requiere alas.</td></tr><tr><td>Party y objetivos</td><td>Kanturu / Raklion</td><td>Evaluá tu equipo, armá una party y elegí el objetivo que podés sostener.</td></tr><tr><td>Competencia</td><td>Swamp / Karutan / Land of Trials</td><td>Buscá zonas disputadas y coordiná con tu party o guild.</td></tr></tbody></table></div></section>
    <section id="sistemas"><span class="eyebrow">03 / LO QUE IMPORTA</span><h2>Decisiones que construyen progreso.</h2><div class="guide-systems"><article><h3>Zen</h3><p>Guardá parte de lo que farmeás y considerá el costo de tu próxima mejora. Vender y administrar tus recursos es parte del recorrido.</p></article><article><h3>Primeras alas</h3><p>El camino a las primeras alas pasa por la Chaos Machine. Revisá los ingredientes y la probabilidad que muestra el juego antes de confirmar una combinación.</p></article><article><h3>Reset por etapas</h3><p>El progreso se organiza por tramos de reset. Consultá el requisito que muestra el juego o tu panel de cuenta antes de resetear.</p></article><article><h3>Master Reset</h3><p>Es un objetivo posterior al recorrido de resets. Revisá sus requisitos dentro del servidor antes de preparar recursos.</p></article></div></section>
    <div class="guide-close"><p>¿Ya está todo listo?</p><a class="btn btn-primary" href="<?php echo __BASE_URL__; ?>downloads/">Ver descargas</a></div>
</div>
