<?php
if(!defined('access') || !access) die();
if(!isLoggedIn()) return;
require_once __DIR__.'/recharge-domain.php';
require_once __DIR__.'/recharge-wallet.php';
require_once __DIR__.'/recharge-management.php';
$rechargeConfig=require __DIR__.'/recharge-config.php';
$rechargeAccount=(string)($_SESSION['username'] ?? '');
$rechargeBalance=panicRechargeWalletBalance($rechargeAccount);
require_once __DIR__.'/recharge-vip-status.php';
$shopVip=panicRechargeVipStatus($rechargeAccount);
$rechargePackages=[];
try { $publicOffers=(new PanicRechargeManagement())->offers(); } catch(Throwable $ignored) { $publicOffers=[]; }
foreach($publicOffers as $package) {
    try { $rechargePackages[]=PanicRecharge::package($package); } catch(InvalidArgumentException $ignored) {}
}
require __DIR__.'/recharge-shop-controller.php';
if(!$rechargePackages) $shopCanBuy=false;
// Editorial highlight only. Offers, prices and bonuses remain controlled by the shop.
$shopHasFeatured=false;
foreach($rechargePackages as $package) if(!empty($package['featured'])) $shopHasFeatured=true;
$shopSpotlightIndex=(int)floor(count($rechargePackages)/2);

$shopFeaturedIndex=$shopSpotlightIndex;
foreach($rechargePackages as $i=>$package) if(!empty($package['featured'])) { $shopFeaturedIndex=$i; break; }
$shopBestValueIndex=$shopFeaturedIndex;
foreach($rechargePackages as $i=>$package) if(($package['coins']+$package['bonus'])*$rechargePackages[$shopBestValueIndex]['price_cents']>($rechargePackages[$shopBestValueIndex]['coins']+$rechargePackages[$shopBestValueIndex]['bonus'])*$package['price_cents']) $shopBestValueIndex=$i;
$shopUniqueBest=true;
foreach($rechargePackages as $i=>$package) if($i!==$shopBestValueIndex && ($package['coins']+$package['bonus'])*$rechargePackages[$shopBestValueIndex]['price_cents']>=($rechargePackages[$shopBestValueIndex]['coins']+$rechargePackages[$shopBestValueIndex]['bonus'])*$package['price_cents']) $shopUniqueBest=false;
if($shopUniqueBest) $shopFeaturedIndex=$shopBestValueIndex;
$shopRecommendation=$shopUniqueBest?'MEJOR VALOR':'RECOMENDADO';
$shopInitialQuantities=$shopQuantities;
if(($_POST['recharge_action'] ?? '')!=='create' && !array_sum(array_map('floatval',$shopInitialQuantities)) && isset($rechargePackages[$shopFeaturedIndex])) $shopInitialQuantities[$rechargePackages[$shopFeaturedIndex]['id']]='1';
$shopBonusIndex=null;
foreach($rechargePackages as $i=>$package) if($package['bonus']>0 && ($shopBonusIndex===null || $package['bonus']*$rechargePackages[$shopBonusIndex]['coins']>$rechargePackages[$shopBonusIndex]['bonus']*$package['coins'])) $shopBonusIndex=$i;
$shopLore=json_decode(file_get_contents(__DIR__.'/atlas-vinculos.json'),true);
$shopCreatures=[]; foreach(($shopLore['entries'] ?? []) as $creature) $shopCreatures[$creature['slug']]=$creature;
try { $shopProducts=(new PanicRechargeManagement())->storefront(); } catch(Throwable $ignored) { $shopProducts=PanicRechargeManagement::storefrontDefaults(); }
$shopVipOffer=$shopProducts['vip'];
$shopMountCopy=['theryon'=>'Que te vean llegar.','nerathys'=>'Tres cabezas. Una presencia.','vaeraxes'=>'El cielo lleva tu nombre.'];
$shopPackOrder=array_values(array_filter(array_keys($rechargePackages),function($i) use ($shopFeaturedIndex) { return $i!==$shopFeaturedIndex; }));
if(isset($rechargePackages[$shopFeaturedIndex])) array_splice($shopPackOrder,(int)floor(count($rechargePackages)/2),0,[$shopFeaturedIndex]);
$shopPackColumns=implode(' ',array_map(function($i) use ($shopFeaturedIndex) { return $i===$shopFeaturedIndex?'minmax(0,1.2fr)':'minmax(0,1fr)'; },$shopPackOrder));
?>
<section class="recharge-shop eryns-store" aria-labelledby="recharge-title" data-recharge-shop>
    <div class="eryns-store-top"><a href="<?php echo __BASE_URL__; ?>usercp/">← Mi cuenta</a><span>MU PANIC <b>/</b> ERYNS</span><a href="#recharge-history">Mis compras</a></div>
    <?php if(!$shopCanBuy) { ?><div class="recharge-notice"><strong>Armá tu próxima recarga</strong><p>Podés probar el selector y comparar cantidades. El pago se habilitará cuando esté listo el servicio de recargas.</p></div><?php } ?>
    <?php if($shopMessage || $shopCreated) { ?><div id="recharge-checkout" class="eryns-checkout-feedback">
    <?php if($shopMessage) { ?><div class="recharge-notice recharge-feedback" role="status"><strong><?php echo panicAccountEscape($shopMessage); ?></strong></div><?php } ?>
    <?php if($shopCreated && isset($shopCreated['checkout_url']) && $shopCreated['payment_state']==='pending') { ?>
    <div class="recharge-ready"><span class="eyebrow">TU COMPRA ESTÁ LISTA</span><h3><?php echo number_format($shopCreated['coins'],0,',','.'); ?> Eryns para <?php echo panicAccountEscape($shopCreated['account']); ?></h3><p>Total: <b>$ <?php echo number_format($shopCreated['price_cents']/100,0,',','.'); ?> ARS</b>. Revisá que Ualá muestre este mismo importe antes de pagar.</p><a class="recharge-button" href="<?php echo panicAccountEscape($shopCreated['checkout_url']); ?>" target="_blank" rel="noopener noreferrer">Continuar a Ualá ↗</a><p class="recharge-subtle">Tu compra ya está guardada en el historial.</p></div>
    <?php } ?>
    </div><?php } ?>
    <?php if($shopAdmin) { ?><p><a class="recharge-button recharge-button-secondary" href="<?php echo panicAccountEscape(__BASE_URL__.'usercp/shopadmin/'); ?>">Administrar tienda →</a></p><?php } ?>

    <header class="eryns-stage"><div class="eryns-stage-art" aria-hidden="true"></div>
        <div class="eryns-stage-copy"><span class="eryns-overline">TU HISTORIA EN PANIC</span><h2 id="recharge-title">Que te vean llegar.<br><em>Que recuerden tu nombre.</em></h2><p>Elegí la presencia que querés llevar a PANIC.</p><a href="#recharge-packages" class="eryns-stage-cta">Conseguí tus Eryns <span aria-hidden="true">↓</span></a></div>
        <span class="eryns-stage-signature">VÍNCULOS / BESTIAS / LEYENDAS</span>
    </header>
    <section class="eryns-wishlist" aria-labelledby="eryns-wishlist-title"><div class="eryns-wishlist-heading"><span class="eryns-overline">LAS BESTIAS PRIMORDIALES</span><h3 id="eryns-wishlist-title">No pases desapercibido.</h3><p>Una presencia que se siente antes de la primera batalla.</p></div><div class="eryns-mount-shelf">
    <?php foreach(($shopProducts['products'] ?? []) as $product) { if(!isset($shopCreatures[$product['slug']])) continue; $creature=$shopCreatures[$product['slug']]; $productPrice=$shopVip!==null && $shopVip['active']?($product['vip_price_coins'] ?? null):$product['price_coins']; $published=!empty($product['available']); $available=$published && is_int($productPrice) && $productPrice>0; ?>
      <article class="eryns-mount-product eryns-mount-product--<?php echo panicAccountEscape($product['slug']); ?> eryns-motion-surface<?php echo !$published?' is-sealed':''; ?>" data-tilt>
        <button type="button" class="eryns-mount-preview" data-open-creature="eryns-creature-<?php echo panicAccountEscape($product['slug']); ?>" aria-label="Ver la historia de <?php echo panicAccountEscape($creature['name']); ?>"><img src="<?php echo __PATH_TEMPLATE__; ?>img/recharge/<?php echo panicAccountEscape($product['slug']); ?>-scene-v5.webp" alt="<?php echo panicAccountEscape($creature['name']); ?> en una escena épica de MU" width="810" height="1080" loading="lazy" decoding="async"><span class="eryns-mount-veil" aria-hidden="true"></span><span class="eryns-mount-sparks" aria-hidden="true"></span><?php if(!$published) { ?><span class="eryns-seal"><svg viewBox="0 0 32 38" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M8 16V9a8 8 0 0116 0v7M4 16h24v19H4zM16 23v6"/></svg><span>SELLADO</span></span><?php } ?></button>
        <div class="eryns-mount-caption"><span><?php echo panicAccountEscape($creature['title']); ?></span><h4><?php echo panicAccountEscape($creature['name']); ?></h4><p class="eryns-mount-status"><?php echo panicAccountEscape($shopMountCopy[$product['slug']] ?? 'Una presencia que se recuerda.'); ?></p><?php if($available) { ?><p class="eryns-mount-price"><?php echo number_format($productPrice,0,',','.'); ?> Eryns<?php echo $shopVip!==null && $shopVip['active']?' · Precio VIP':' · Precio normal'; ?></p><?php } ?><button type="button" data-target-price="<?php echo $available?$productPrice:0; ?>" data-target-name="<?php echo panicAccountEscape($creature['name']); ?>" <?php if(!$available) echo 'disabled'; ?>><?php echo $available?'Recargar para este →':($published?'Precio VIP por confirmar':'Se revela en la apertura'); ?></button></div>
      </article><?php } ?>
      <article class="eryns-mount-product eryns-mount-secret eryns-motion-surface" data-tilt aria-label="Cuarta tarjeta misteriosa, se revela en la apertura"><div class="eryns-secret-scene" aria-hidden="true"><span class="eryns-secret-question">?</span><span class="eryns-mount-sparks"></span><span class="eryns-seal"><svg viewBox="0 0 32 38" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M8 16V9a8 8 0 0116 0v7M4 16h24v19H4zM16 23v6"/></svg><span>SELLADO</span></span></div><div class="eryns-mount-caption"><span>UN SECRETO DE PANIC</span><h4>Lo desconocido.</h4><p>Hay historias que todavía no viste.</p><span class="eryns-secret-reveal">Se revela en la apertura</span></div></article>
    </div><p class="eryns-target-message" data-target-message role="status"></p></section>
    <?php require __DIR__.'/recharge-vip-showcase.php'; ?>
    <section id="recharge-packages" class="eryns-buy eryns-buy--market" aria-labelledby="eryns-buy-title">
      <form id="eryns-purchase-form" method="post" action="<?php echo panicAccountEscape(__BASE_URL__.'usercp/recharge/#recharge-checkout'); ?>" data-cart-form>
        <div class="eryns-buy-heading"><div><span class="eryns-overline">TIENDA DE ERYNS</span><h3 id="eryns-buy-title">Elegí tu pack de Eryns.</h3></div><aside class="eryns-vault"><img src="<?php echo __PATH_TEMPLATE__; ?>img/recharge/eryns-pack-chest.webp" alt="" width="88" height="88"><div><span>La bóveda de <?php echo panicAccountEscape($rechargeAccount); ?></span><strong><?php echo $rechargeBalance===null?'Saldo no disponible':number_format($rechargeBalance,0,',','.').' Eryns'; ?></strong></div></aside></div>
        <input type="hidden" name="recharge_csrf" value="<?php echo panicAccountEscape($_SESSION['recharge_csrf']); ?>">
        <input type="hidden" name="recharge_nonce" value="<?php echo panicAccountEscape($_SESSION['recharge_nonce']); ?>">
        <input type="hidden" name="recharge_action" value="create">
        <div class="eryns-pack-picker"><span class="eryns-swipe-hint">Deslizá para ver los packs →</span><div class="eryns-denominations" style="--eryns-pack-columns:<?php echo $shopPackColumns; ?>" role="group" aria-label="Elegí una recarga"><?php foreach($shopPackOrder as $i) { $package=$rechargePackages[$i]; $artTier=$i>=count($rechargePackages)-1?'legendary':($i>=count($rechargePackages)/3?'chest':'pouch'); $bonusPercent=100*$package['bonus']/$package['coins']; ?><button type="button" data-tilt class="eryns-denomination eryns-pack-card eryns-motion-surface eryns-pack-card--<?php echo $artTier; ?><?php echo $i===$shopFeaturedIndex?' eryns-denomination--featured':''; ?>" data-choose-package="<?php echo panicAccountEscape($package['id']); ?>" aria-pressed="false"><?php if($i===$shopFeaturedIndex) { ?><span class="eryns-card-recommendation"><?php echo $shopRecommendation; ?></span><?php } ?><img src="<?php echo __PATH_TEMPLATE__; ?>img/recharge/eryns-pack-<?php echo $artTier; ?>.webp" alt="" width="1024" height="1024" decoding="async"><strong><?php echo number_format($package['coins']+$package['bonus'],0,',','.'); ?></strong><small>Eryns</small><span class="eryns-pack-dust" aria-hidden="true"></span><em class="eryns-card-bonus<?php echo $package['bonus']>0?' has-bonus':''; ?>">+<?php echo number_format($bonusPercent,$bonusPercent==floor($bonusPercent)?0:1,',','.'); ?>% EXTRA</em><span class="eryns-card-breakdown"><?php echo number_format($package['coins'],0,',','.'); ?> + <?php echo number_format($package['bonus'],0,',','.'); ?> de regalo</span><b class="eryns-card-price">$ <?php echo number_format($package['price_cents']/100,0,',','.'); ?> <small>ARS</small></b><span class="eryns-card-choice">Elegir pack</span></button><?php } ?></div></div>
        <div id="recharge-cart" class="eryns-offer-grid" aria-labelledby="cart-title">
          <div class="eryns-selected-deal"><div class="eryns-selected-copy"><span class="eryns-deal-label" id="cart-title" data-selected-name>RECIBÍS EN TU CUENTA</span><div class="eryns-real-bonus" data-bonus-row hidden><strong data-bonus-rate></strong><span>EXTRA</span></div><strong class="eryns-deal-amount" data-total-coins>0 <small>Eryns</small></strong><p class="eryns-deal-breakdown" data-bonus-breakdown hidden></p><p class="eryns-deal-promise">Saldo para elegir lo que querés en PANIC.</p></div></div>
          <div class="eryns-purchase-action"><span>TOTAL A PAGAR</span><strong data-total-price>$ 0 ARS</strong><p class="eryns-price-includes" data-price-includes>Pago único. Sin suscripción.</p><button class="recharge-button" type="submit" data-cart-submit data-enabled="<?php echo $shopCanBuy?'1':'0'; ?>" <?php if(!$shopCanBuy) echo 'disabled'; ?>><?php echo $shopCanBuy?'Pagar con Ualá →':'Pagos próximamente'; ?></button><p class="eryns-payment-explanation">Continuás en <b>Ualá</b> para completar el pago.</p><p data-cart-hint>Tu recarga va a la cuenta de arriba.</p></div>
        </div>
        <?php if($shopBonusIndex!==null) { $bonusOffer=$rechargePackages[$shopBonusIndex]; ?><button type="button" class="eryns-upgrade" data-upgrade-package="<?php echo panicAccountEscape($bonusOffer['id']); ?>" data-upgrade-coins="<?php echo $bonusOffer['coins']+$bonusOffer['bonus']; ?>" data-upgrade-price="<?php echo $bonusOffer['price_cents']; ?>" hidden><span><strong>Recibí <?php echo number_format($bonusOffer['bonus'],0,',','.'); ?> Eryns extra</strong><small>Pack de <?php echo number_format($bonusOffer['coins']+$bonusOffer['bonus'],0,',','.'); ?> · $ <?php echo number_format($bonusOffer['price_cents']/100,0,',','.'); ?> ARS</small></span><b>Elegir pack →</b></button><?php } ?>
      </form>
      <div class="eryns-confidence"><span><b>Pago con Ualá</b> Completás el pago en su página</span><span><b>Eryns para tu cuenta</b> Los comparten tus personajes</span><span><b>Acreditación automática</b> Desconectate del juego para recibirla</span></div>
    </section>
<?php $creature=$shopCreatures['theryon']; ?><dialog class="eryns-creature-dialog" id="eryns-creature-<?php echo 'theryon'; ?>" aria-labelledby="eryns-creature-title-<?php echo 'theryon'; ?>"><button type="button" class="eryns-dialog-close" data-close-creature aria-label="Cerrar presentación">×</button><div class="eryns-dialog-grid"><img src="<?php echo __PATH_TEMPLATE__.'img/recharge/'.panicAccountEscape($creature['slug']).'-scene-v5.webp'; ?>" alt="<?php echo panicAccountEscape($creature['name']); ?>" width="1024" height="1024" loading="lazy"><div><span class="eryns-overline"><?php echo panicAccountEscape($creature['title']); ?></span><h3 id="eryns-creature-title-<?php echo 'theryon'; ?>"><?php echo panicAccountEscape($creature['name']); ?></h3><p><?php echo panicAccountEscape($creature['role']); ?></p><ul><?php foreach($creature['stats'] as $stat) { ?><li><?php echo panicAccountEscape($stat); ?></li><?php } ?></ul><p class="eryns-availability"><?php echo panicAccountEscape($creature['obtain']); ?>. Precios y disponibilidad: X / F11 → Tienda.</p><button type="button" class="eryns-dialog-buy" data-return-to-buy>Volver a elegir Eryns →</button></div></div></dialog>
    <?php foreach(['nerathys','vaeraxes'] as $slug) { $creature=$shopCreatures[$slug]; ?><dialog class="eryns-creature-dialog" id="eryns-creature-<?php echo $slug; ?>" aria-labelledby="eryns-creature-title-<?php echo $slug; ?>"><button type="button" class="eryns-dialog-close" data-close-creature aria-label="Cerrar presentación">×</button><div class="eryns-dialog-grid"><img src="<?php echo __PATH_TEMPLATE__.'img/recharge/'.panicAccountEscape($creature['slug']).'-scene-v5.webp'; ?>" alt="<?php echo panicAccountEscape($creature['name']); ?>" width="1024" height="1024" loading="lazy"><div><span class="eryns-overline"><?php echo panicAccountEscape($creature['title']); ?></span><h3 id="eryns-creature-title-<?php echo $slug; ?>"><?php echo panicAccountEscape($creature['name']); ?></h3><p><?php echo panicAccountEscape($creature['role']); ?></p><ul><?php foreach($creature['stats'] as $stat) { ?><li><?php echo panicAccountEscape($stat); ?></li><?php } ?></ul><p class="eryns-availability"><?php echo panicAccountEscape($creature['obtain']); ?>.</p><button type="button" class="eryns-dialog-buy" data-return-to-buy>Volver a elegir Eryns →</button></div></div></dialog><?php } ?>
    <div class="eryns-thanks"><span>HECHO PARA SEGUIR JUGANDO.</span><p>Cada recarga ayuda a mantener y desarrollar MU PANIC.<br><b>Gracias por construir este mundo con nosotros.</b></p></div>
    <div class="eryns-purchase-utilities">        <details class="eryns-combine"><summary>¿Querés otra cantidad? Combiná paquetes</summary><div class="eryns-quantity-list"><?php foreach($rechargePackages as $package) { ?><div class="eryns-quantity-row" data-package data-bonus="<?php echo $package['bonus']; ?>" data-base-coins="<?php echo $package['coins']; ?>" data-coins="<?php echo $package['coins']+$package['bonus']; ?>" data-price="<?php echo $package['price_cents']; ?>" data-title="<?php echo panicAccountEscape(panicAccountCurrencyLabel($package['title'])); ?>"><div><label for="quantity-<?php echo $package['id']; ?>"><?php echo number_format($package['coins']+$package['bonus'],0,',','.'); ?> Eryns</label><small>$ <?php echo number_format($package['price_cents']/100,0,',','.'); ?> ARS por paquete<?php if($package['bonus']>0) { ?> · <?php echo number_format($package['bonus'],0,',','.'); ?> extra incluido<?php } ?></small><p data-line-total>Sin seleccionar</p></div><div class="eryns-stepper"><button type="button" data-quantity-change="-1" aria-label="Quitar un paquete de <?php echo $package['coins']+$package['bonus']; ?> Eryns">−</button><input id="quantity-<?php echo $package['id']; ?>" form="eryns-purchase-form" name="quantity[<?php echo $package['id']; ?>]" type="number" inputmode="numeric" min="0" max="99" step="1" value="<?php echo panicAccountEscape($shopInitialQuantities[$package['id']] ?? '0'); ?>"><button type="button" data-quantity-change="1" aria-label="Agregar un paquete de <?php echo $package['coins']+$package['bonus']; ?> Eryns">+</button></div></div><?php } ?></div><div data-cart-lines class="eryns-cart-lines"></div><small>Hasta 99 unidades por paquete y $1.000.000 por compra. Los bonos activos se incluyen en el total.</small></details>
        <details class="eryns-terms-details"><summary>Términos de compra</summary><p class="eryns-terms">Al continuar aceptás los <a href="<?php echo __BASE_URL__; ?>tos/" target="_blank" rel="noopener">Términos</a>, la <a href="<?php echo __BASE_URL__; ?>refunds/" target="_blank" rel="noopener">política de compras y reembolsos</a> y la <a href="<?php echo __BASE_URL__; ?>privacy/" target="_blank" rel="noopener">Privacidad</a>.</p></details>
</div>
    <div class="eryns-utilities"><details id="recharge-history" class="eryns-support-panel"><summary><span><?php echo panicAccountIcon('coin'); ?></span><div><strong>Mis compras</strong><small>Historial y estado de tus recargas</small></div><b><?php echo (int)$shopHistory['total']; ?> <i aria-hidden="true">+</i></b></summary><div class="eryns-support-body">        <?php if(!$shopHistory['orders']) { ?><div class="recharge-history-empty"><span class="recharge-gem" aria-hidden="true"><?php echo panicAccountIcon('coin'); ?></span><strong>Acá empieza tu historial</strong><p>Cuando prepares una compra, la vas a encontrar acá con su precio y estado.</p></div><?php } ?>
        <div class="recharge-history-list"><?php foreach($shopHistory['orders'] as $order) { [$tone,$label,$copy]=panicRechargeStatus($order); ?>
            <article class="recharge-order" data-order-id="<?php echo $order['id']; ?>" data-order-state="<?php echo $tone; ?>"><div class="recharge-order-top"><span class="recharge-order-date"><?php echo panicAccountEscape(panicRechargeArgDate($order['created_at'])); ?> ARG</span><span class="recharge-status" data-order-label><?php echo panicAccountEscape($label); ?></span></div><div class="recharge-order-value"><strong><?php echo number_format($order['coins'],0,',','.'); ?> <small>Eryns</small></strong><b>$ <?php echo number_format($order['price_cents']/100,0,',','.'); ?> ARS</b></div><p data-order-copy><?php echo panicAccountEscape($copy); ?></p><div class="recharge-order-actions"><?php if($order['payment_state']==='pending' && isset($order['checkout_url'])) { ?><a class="recharge-button recharge-button-secondary" data-order-pay href="<?php echo panicAccountEscape($order['checkout_url']); ?>" target="_blank" rel="noopener noreferrer">Continuar pago ↗</a><?php } ?><?php if($shopSettings && $order['live']===($shopSettings['environment']==='production') && $order['payment_state']!=='creating') { ?><form method="post" action="<?php echo panicAccountEscape(__BASE_URL__.'usercp/recharge/#recharge-history'); ?>"><input type="hidden" name="recharge_csrf" value="<?php echo panicAccountEscape($_SESSION['recharge_csrf']); ?>"><input type="hidden" name="order_id" value="<?php echo $order['id']; ?>"><button type="submit" name="recharge_action" value="refresh" class="recharge-text-button">Actualizar estado</button></form><?php } ?></div><details><summary>Ver detalle y número de compra</summary><ul><?php foreach($order['lines'] as $line) { ?><li><?php echo $line['quantity']; ?> × <?php echo panicAccountEscape(panicAccountCurrencyLabel($line['title'])); ?></li><?php } ?></ul><p>Cuenta: <b><?php echo panicAccountEscape($order['account']); ?></b><br><span class="recharge-order-reference"><?php echo $order['id']; ?></span></p></details></article>
        <?php } ?></div>
        <?php if($shopHistory['total']>10) { ?><nav class="recharge-pagination" aria-label="Páginas de compras"><?php if($shopPage>1) { ?><a href="?compras=<?php echo $shopPage-1; ?>#recharge-history">← Anteriores</a><?php } ?><span>Página <?php echo $shopPage; ?> de <?php echo (int)ceil($shopHistory['total']/10); ?></span><?php if($shopPage*10<$shopHistory['total']) { ?><a href="?compras=<?php echo $shopPage+1; ?>#recharge-history">Siguientes →</a><?php } ?></nav><?php } ?>
        <p class="recharge-subtle" data-history-update role="status">Los estados se actualizan mientras mantenés esta página abierta.</p>
</div></details>
    <details id="recharge-guide" class="eryns-support-panel"><summary><span><?php echo panicAccountIcon('shield'); ?></span><div><strong>¿Cómo recibo mis Eryns?</strong><small>Pago, entrega y preguntas frecuentes</small></div><b aria-hidden="true">+</b></summary><div class="eryns-support-body"><ol class="eryns-help-steps"><li><b>1. Elegí tu pack</b><span>Revisá la cantidad, el precio y la cuenta de destino.</span></li><li><b>2. Pagá con Ualá</b><span>Prepará el enlace y completá el pago en su página.</span></li><li><b>3. Recibilos en el juego</b><span>Con el pago aprobado, desconectate. La acreditación se completa automáticamente.</span></li></ol><details><summary>¿Dónde puedo usarlos?</summary><p>En la tienda del juego: X o F11 → Tienda. Los Eryns pertenecen a tu cuenta y los comparten sus personajes.</p></details><details><summary>¿Qué pasa si estoy jugando?</summary><p>La recarga espera a que cierres la sesión del juego. Después se reintenta la entrega automáticamente. No hace falta volver a pagar.</p></details><details><summary>¿Cómo compruebo la entrega?</summary><p>Abrí Mis compras. «Eryns acreditados» confirma la entrega. Volvé a entrar al juego para ver el saldo. Si aparece «En revisión», contactá al equipo con el número de compra.</p></details></div></details></div>
    <div class="eryns-mobile-summary" data-mobile-summary hidden><div><strong data-mobile-coins>0 Eryns</strong><span data-mobile-price>$ 0 ARS</span></div><button type="submit" form="eryns-purchase-form" data-mobile-submit <?php if(!$shopCanBuy) echo 'disabled'; ?>><?php echo $shopCanBuy?'Pagar con Ualá':'Pagos próximamente'; ?></button></div>
    <?php if($shopAdmin) { ?><details class="recharge-admin"><summary>Administración · recargas y prueba anterior</summary><div class="recharge-admin-content"><p>Ambiente: <b><?php echo panicAccountEscape($shopSettings['environment'] ?? 'Sin configurar'); ?></b>.</p><p>Las compras de jugadores usan su propio historial y registro de entrega. La prueba anterior de pruebacoin se conserva por separado.</p><?php include __DIR__.'/recharge-check.php'; include __DIR__.'/recharge-pilot-panel.php'; ?><?php if($shopStore) { $adminHistory=$shopStore->history('',1,true); ?><h3>Últimas compras del servidor</h3><?php foreach($adminHistory['orders'] as $entry) { [, $statusText]=panicRechargeStatus($entry); ?><p><b><?php echo panicAccountEscape($entry['account']); ?></b> · <?php echo number_format($entry['coins'],0,',','.'); ?> Eryns · <?php echo panicAccountEscape($statusText); ?><br><small class="recharge-order-reference"><?php echo $entry['id']; ?></small></p><?php } } ?></div></details><?php } ?>
</section>
