<?php
if(!defined('access') || !access) die();
if(!isLoggedIn()) return;
require_once __DIR__.'/recharge-domain.php';
require_once __DIR__.'/recharge-wallet.php';
$rechargeConfig=require __DIR__.'/recharge-config.php';
$rechargeAccount=(string)($_SESSION['username'] ?? '');
$rechargeBalance=panicRechargeWalletBalance($rechargeAccount);
$rechargePackages=[];
foreach($rechargeConfig['packages'] as $package) {
    try { $rechargePackages[]=PanicRecharge::package($package); } catch(InvalidArgumentException $ignored) {}
}
require __DIR__.'/recharge-shop-controller.php';
?>
<section class="recharge-shop" aria-labelledby="recharge-title" data-recharge-shop>
    <header class="recharge-hero">
        <span class="eyebrow">MU PANIC / WCOIN C</span>
        <h2 id="recharge-title">Tu próxima conquista<br><em>empieza acá.</em></h2>
        <p>Elegí tus monedas. Combiná paquetes. Seguí tu recarga hasta que llegue al juego.</p>
        <div class="recharge-wallet-row"><div class="recharge-account"><span>TU CUENTA</span><strong><?php echo panicAccountEscape($rechargeAccount); ?></strong></div><div class="recharge-account recharge-balance"><span>TUS WCOIN C</span><strong><?php echo $rechargeBalance===null?'Saldo no disponible':number_format($rechargeBalance,0,',','.'); ?></strong></div></div>
        <small class="recharge-balance-note">Saldo consultado al abrir la página. Las monedas se usan en la tienda del juego.</small>
    </header>
    <?php if(!$shopCanBuy) { ?><div class="recharge-notice"><strong>Armá tu próxima recarga</strong><p>Podés probar el selector y comparar cantidades. El pago se habilitará cuando esté listo el servicio de recargas.</p></div><?php } ?>
    <?php if($shopMessage) { ?><div class="recharge-notice recharge-feedback" role="status"><strong><?php echo panicAccountEscape($shopMessage); ?></strong></div><?php } ?>
    <?php if($shopCreated && isset($shopCreated['checkout_url']) && $shopCreated['payment_state']==='pending') { ?>
    <div class="recharge-ready"><span class="eyebrow">TU COMPRA ESTÁ LISTA</span><h3><?php echo number_format($shopCreated['coins'],0,',','.'); ?> WCoin C para <?php echo panicAccountEscape($shopCreated['account']); ?></h3><p>Total: <b>$ <?php echo number_format($shopCreated['price_cents']/100,0,',','.'); ?> ARS</b>. Revisá que Ualá muestre este mismo importe antes de pagar.</p><a class="recharge-button" href="<?php echo panicAccountEscape($shopCreated['checkout_url']); ?>" target="_blank" rel="noopener noreferrer">Continuar a Ualá ↗</a><p class="recharge-subtle">Tu compra ya está guardada en el historial.</p></div>
    <?php } ?>
    <nav class="recharge-sections" aria-label="Secciones de recargas"><a href="#recharge-packages">Elegir monedas</a><a href="#recharge-history">Mis compras</a><a href="#recharge-guide">Cómo funciona</a></nav>
    <section id="recharge-packages" class="recharge-section">
        <div class="recharge-section-head"><div><span class="eyebrow">01 / ARMÁ TU RECARGA</span><h3>Más monedas. Más aventura.</h3></div><span>$1 ARS = 1 WCoin C</span></div>
        <form method="post" action="<?php echo panicAccountEscape(__BASE_URL__.'usercp/recharge/#recharge-history'); ?>" class="recharge-builder" data-cart-form>
            <input type="hidden" name="recharge_csrf" value="<?php echo panicAccountEscape($_SESSION['recharge_csrf']); ?>">
            <input type="hidden" name="recharge_nonce" value="<?php echo panicAccountEscape($_SESSION['recharge_nonce']); ?>">
            <input type="hidden" name="recharge_action" value="create">
            <div class="recharge-packages"><?php foreach($rechargePackages as $index=>$package) { ?>
            <article class="recharge-package<?php echo $index===4?' recharge-package-featured':''; ?>" data-package data-coins="<?php echo $package['coins']; ?>" data-price="<?php echo $package['price_cents']; ?>" data-title="<?php echo panicAccountEscape($package['title']); ?>">
                <div class="recharge-package-top"><span class="recharge-gem" aria-hidden="true"><?php echo panicAccountIcon('gem'); ?></span><span class="recharge-tier"><?php echo ['EL PRIMER PASO','SEGUÍ AVANZANDO','PREPARÁ TU AVENTURA','SUBÍ LA APUESTA','A LO GRANDE'][$index] ?? 'TU RECARGA'; ?></span></div>
                <h4><?php echo number_format($package['coins'],0,',','.'); ?><small>WCoin C</small></h4>
                <div class="recharge-price">$ <?php echo number_format($package['price_cents']/100,0,',','.'); ?><small> ARS por paquete</small></div>
                <label class="recharge-quantity-label" for="quantity-<?php echo $package['id']; ?>">Cantidad de paquetes</label>
                <div class="recharge-quantity"><button type="button" data-quantity-change="-1" aria-label="Quitar un paquete de <?php echo number_format($package['coins'],0,',','.'); ?> monedas">−</button><input id="quantity-<?php echo $package['id']; ?>" name="quantity[<?php echo $package['id']; ?>]" type="number" inputmode="numeric" min="0" max="99" step="1" value="<?php echo panicAccountEscape($shopQuantities[$package['id']] ?? '0'); ?>"><button type="button" data-quantity-change="1" aria-label="Agregar un paquete de <?php echo number_format($package['coins'],0,',','.'); ?> monedas">+</button></div>
                <p class="recharge-line-total" data-line-total>Elegí cuántos querés</p>
            </article><?php } ?></div>
            <aside class="recharge-cart" aria-labelledby="cart-title"><span class="eyebrow">TU RECARGA</span><h3 id="cart-title">Todo claro,<br>antes de pagar.</h3><div data-cart-lines class="recharge-cart-lines"><p>Sumá paquetes con + o escribí una cantidad.</p></div><div class="recharge-cart-total"><span>Recibís en tu cuenta</span><strong data-total-coins>0 <small>WCoin C</small></strong><span>Total a pagar</span><b data-total-price>$ 0 <small>ARS</small></b></div><p class="recharge-destination">Destino: <b><?php echo panicAccountEscape($rechargeAccount); ?></b></p><button class="recharge-button" type="submit" data-cart-submit data-enabled="<?php echo $shopCanBuy?'1':'0'; ?>" <?php if(!$shopCanBuy) echo 'disabled'; ?>><?php echo $shopCanBuy?'Pagar con Ualá':'Pagos próximamente'; ?></button><p class="recharge-cart-hint" data-cart-hint>Un solo pago. Todas tus monedas.</p><small>Hasta 99 unidades por paquete y $1.000.000 por compra. Sin bonos adicionales.</small><noscript><p>Podés escribir las cantidades y continuar. El servidor calculará el total antes de mostrar el enlace de pago.</p></noscript></aside>
        </form>
    </section>
    <section id="recharge-history" class="recharge-section">
        <div class="recharge-section-head"><div><span class="eyebrow">02 / SEGUÍ TU RECARGA</span><h3>Mis compras</h3></div><span>Actualización automática de estados</span></div>
        <?php if(!$shopHistory['orders']) { ?><div class="recharge-history-empty"><span class="recharge-gem" aria-hidden="true"><?php echo panicAccountIcon('coin'); ?></span><strong>Tu próxima aventura todavía no tiene recibo</strong><p>Cuando prepares una compra, la vas a encontrar acá con su precio y estado.</p></div><?php } ?>
        <div class="recharge-history-list"><?php foreach($shopHistory['orders'] as $order) { [$tone,$label,$copy]=panicRechargeStatus($order); ?>
            <article class="recharge-order" data-order-id="<?php echo $order['id']; ?>" data-order-state="<?php echo $tone; ?>"><div class="recharge-order-top"><span class="recharge-order-date"><?php echo panicAccountEscape(date('d/m/Y · H:i',strtotime($order['created_at'])-3*3600)); ?> ARG</span><span class="recharge-status" data-order-label><?php echo panicAccountEscape($label); ?></span></div><div class="recharge-order-value"><strong><?php echo number_format($order['coins'],0,',','.'); ?> <small>WCoin C</small></strong><b>$ <?php echo number_format($order['price_cents']/100,0,',','.'); ?> ARS</b></div><p data-order-copy><?php echo panicAccountEscape($copy); ?></p><div class="recharge-order-actions"><?php if($order['payment_state']==='pending' && isset($order['checkout_url'])) { ?><a class="recharge-button recharge-button-secondary" data-order-pay href="<?php echo panicAccountEscape($order['checkout_url']); ?>" target="_blank" rel="noopener noreferrer">Continuar pago ↗</a><?php } ?><?php if($shopSettings && $order['live']===($shopSettings['environment']==='production') && $order['payment_state']!=='creating') { ?><form method="post" action="<?php echo panicAccountEscape(__BASE_URL__.'usercp/recharge/#recharge-history'); ?>"><input type="hidden" name="recharge_csrf" value="<?php echo panicAccountEscape($_SESSION['recharge_csrf']); ?>"><input type="hidden" name="order_id" value="<?php echo $order['id']; ?>"><button type="submit" name="recharge_action" value="refresh" class="recharge-text-button">Actualizar estado</button></form><?php } ?></div><details><summary>Ver detalle y número de compra</summary><ul><?php foreach($order['lines'] as $line) { ?><li><?php echo $line['quantity']; ?> × <?php echo panicAccountEscape($line['title']); ?></li><?php } ?></ul><p>Cuenta: <b><?php echo panicAccountEscape($order['account']); ?></b><br><span class="recharge-order-reference"><?php echo $order['id']; ?></span></p></details></article>
        <?php } ?></div>
        <?php if($shopHistory['total']>10) { ?><nav class="recharge-pagination" aria-label="Páginas de compras"><?php if($shopPage>1) { ?><a href="?compras=<?php echo $shopPage-1; ?>#recharge-history">← Anteriores</a><?php } ?><span>Página <?php echo $shopPage; ?> de <?php echo (int)ceil($shopHistory['total']/10); ?></span><?php if($shopPage*10<$shopHistory['total']) { ?><a href="?compras=<?php echo $shopPage+1; ?>#recharge-history">Siguientes →</a><?php } ?></nav><?php } ?>
        <p class="recharge-subtle" data-history-update role="status">Los estados se actualizan mientras mantenés esta página abierta.</p>
    </section>
    <section id="recharge-guide" class="recharge-section"><div class="recharge-section-head"><div><span class="eyebrow">03 / DE LA WEB AL JUEGO</span><h3>Tres pasos. Tu cuenta lista.</h3></div></div><ol class="recharge-steps"><li><span>1</span><strong>Armá tu recarga</strong><p>Combiná paquetes y cantidades. Revisá el total y la cuenta de destino.</p></li><li><span>2</span><strong>Pagá con Ualá</strong><p>Completá el pago en su página. Nunca ingreses datos de tarjeta en MU PANIC.</p></li><li><span>3</span><strong>Recibí tus monedas</strong><p>Con el pago aprobado, desconectate del juego. La entrega se completa automáticamente y queda registrada acá.</p></li></ol><details><summary>¿Dónde uso mis WCoin C?</summary><p>En el Cash Shop, la tienda dentro del juego. Las monedas corresponden a tu cuenta y las comparten sus personajes.</p></details><details><summary>¿Qué pasa si estoy jugando cuando pago?</summary><p>La compra queda pendiente de entrega hasta que cierres la sesión del juego. Luego el servicio vuelve a intentar la acreditación. No hace falta volver a pagar.</p></details><details><summary>¿Cómo sé si llegó mi recarga?</summary><p>En Mis compras vas a ver «Monedas acreditadas». Volvé a entrar al juego para consultar el saldo actualizado. Si dice «En revisión», contactá al equipo con el número de compra.</p></details></section>
    <?php if($shopAdmin) { ?><details class="recharge-admin"><summary>Administración · recargas y prueba anterior</summary><div class="recharge-admin-content"><p>Ambiente: <b><?php echo panicAccountEscape($shopSettings['environment'] ?? 'Sin configurar'); ?></b>.</p><p>Las compras de jugadores usan su propio historial y registro de entrega. La prueba anterior de pruebacoin se conserva por separado.</p><?php include __DIR__.'/recharge-check.php'; include __DIR__.'/recharge-pilot-panel.php'; ?><?php if($shopStore) { $adminHistory=$shopStore->history('',1,true); ?><h3>Últimas compras del servidor</h3><?php foreach($adminHistory['orders'] as $entry) { [, $statusText]=panicRechargeStatus($entry); ?><p><b><?php echo panicAccountEscape($entry['account']); ?></b> · <?php echo number_format($entry['coins'],0,',','.'); ?> WCoin C · <?php echo panicAccountEscape($statusText); ?><br><small class="recharge-order-reference"><?php echo $entry['id']; ?></small></p><?php } } ?></div></details><?php } ?>
</section>
