<?php
if(!defined('access') || !access) die();
require_once __DIR__.'/recharge-orders.php';
if(!panicRechargeAdminAllowed()) { http_response_code(403); echo 'Acceso no autorizado.'; return; }
if(!is_string($_SESSION['shop_admin_csrf'] ?? null)) $_SESSION['shop_admin_csrf']=bin2hex(random_bytes(32));
$adminMessage=null; $adminError=false; $management=null; $adminStore=null; $adminGateway=null; $adminSettings=null;
$adminCatalogue=['revision'=>0,'packages'=>[]]; $worker=[]; $adminOrders=['total'=>0,'orders'=>[],'summary'=>['total'=>0,'approved_cents'=>0,'delivered_coins'=>0,'pending'=>0,'review'=>0]];
$adminStorefront=PanicRechargeManagement::storefrontDefaults();
$adminPage=max(1,min(250,(int)($_GET['pagina'] ?? 1)));
$adminFilters=['query'=>is_string($_GET['buscar'] ?? null)?substr($_GET['buscar'],0,120):'',
    'state'=>in_array($_GET['estado'] ?? '',['pending','approved','credited','review','creating','rejected'],true)?$_GET['estado']:'',
    'environment'=>in_array($_GET['ambiente'] ?? 'test',['test','production','all'],true)?($_GET['ambiente'] ?? 'test'):'test'];
try {
    $management=new PanicRechargeManagement(); $adminCatalogue=$management->catalogue(); $adminStorefront=$management->storefront(); $worker=$management->worker();
    $adminStore=new PanicRechargeOrders();
    try { [$adminGateway,$adminMerchant,$adminSettings]=panicRechargeShopGateway(); } catch(Throwable $ignored) {}
    if(($_SERVER['REQUEST_METHOD'] ?? '')==='POST') {
        if(!is_string($_POST['admin_csrf'] ?? null) || !hash_equals($_SESSION['shop_admin_csrf'],$_POST['admin_csrf'])) throw new RuntimeException('La sesión venció. Recargá la página.');
        if(($_POST['admin_action'] ?? '')==='catalogue') {
            if(!is_array($_POST['packages'] ?? null) || count($_POST['packages'])>13) throw new InvalidArgumentException('Revisá el catálogo.');
            $rows=[];
            foreach($_POST['packages'] as $input) {
                if(!is_array($input)) throw new InvalidArgumentException('Paquete inválido.');
                $id=$input['id'] ?? ''; $coins=$input['coins'] ?? ''; $bonus=$input['bonus'] ?? '0';
                if($id==='' && ($coins==='' || $coins==='0')) continue;
                foreach([$coins,$bonus] as $value) if(!is_string($value) || !preg_match('/^(0|[1-9][0-9]{0,6})$/D',$value)) throw new InvalidArgumentException('Usá monedas y bonos enteros.');
                $row=['id'=>$id,'title'=>$input['title'] ?? '', 'coins'=>(int)$coins,'price_cents'=>(int)$coins*100,'bonus'=>(int)$bonus,
                    'enabled'=>isset($input['enabled']),'featured'=>isset($input['featured']),'starts_at'=>'','ends_at'=>''];
                foreach(['starts_at','ends_at'] as $key) {
                    $value=$input[$key] ?? ''; if(!is_string($value)) throw new InvalidArgumentException('Fecha inválida.');
                    if($value!=='') {
                        $date=DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',$value,new DateTimeZone('America/Argentina/Buenos_Aires'));
                        if(!$date || $date->format('Y-m-d\TH:i')!==$value) throw new InvalidArgumentException('Fecha inválida.');
                        $row[$key]=$date->format('Y-m-d\TH:iP');
                    }
                }
                $position=$input['position'] ?? ''; if(!is_string($position) || !preg_match('/^(?:[1-9]|1[0-2])$/D',$position)) throw new InvalidArgumentException('Posición inválida.');
                $row['position']=(int)$position; $rows[]=$row;
            }
            if(!is_string($_POST['revision'] ?? null) || !preg_match('/^[0-9]{1,10}$/D',$_POST['revision'])) throw new InvalidArgumentException('Revisión inválida.');
            usort($rows,function($a,$b) { return $a['position']<=>$b['position']; });
            $adminCatalogue=$management->saveCatalogue($rows,(int)$_POST['revision']);
            $adminMessage='Catálogo guardado. Las compras anteriores conservan sus importes y monedas.';
        } elseif(($_POST['admin_action'] ?? '')==='storefront') {
            if(!is_string($_POST['storefront_revision'] ?? null) || !preg_match('/^[0-9]{1,10}$/D',$_POST['storefront_revision'])) throw new InvalidArgumentException('Revisión inválida.');
            $readOptional=function($value) {
                if($value==='') return null;
                if(!is_string($value) || !preg_match('/^[1-9][0-9]{0,6}$/D',$value)) throw new InvalidArgumentException('Usá números enteros positivos o dejá el campo vacío.');
                return (int)$value;
            };
            $presentation=['products'=>[],'vip'=>[]];
            foreach(['theryon','nerathys','vaeraxes'] as $slug) {
                $input=$_POST['products'][$slug] ?? null;
                if(!is_array($input)) throw new InvalidArgumentException('Revisá las monturas.');
                $presentation['products'][]=['slug'=>$slug,'price_coins'=>$readOptional($input['price_coins'] ?? ''),'vip_price_coins'=>$readOptional($input['vip_price_coins'] ?? ''),'available'=>isset($input['available'])];
            }
            $vipInput=$_POST['vip'] ?? null;if(!is_array($vipInput)) throw new InvalidArgumentException('Revisá el plan VIP.');
            $presentation['vip']=['name'=>$vipInput['name'] ?? '', 'days'=>$readOptional($vipInput['days'] ?? ''),'price_coins'=>$readOptional($vipInput['price_coins'] ?? ''),'benefits'=>[]];
            for($benefitIndex=0;$benefitIndex<6;$benefitIndex++) {
                $input=$vipInput['benefits'][$benefitIndex] ?? null;if(!is_array($input)) throw new InvalidArgumentException('Revisá los beneficios.');
                $presentation['vip']['benefits'][]=['title'=>$input['title'] ?? '','detail'=>$input['detail'] ?? '','enabled'=>isset($input['enabled'])];
            }
            $adminStorefront=$management->saveStorefront($presentation,(int)$_POST['storefront_revision']);
            $adminMessage='Vitrina y único plan VIP guardados en la web. La configuración del juego no se modificó.';
        } elseif(($_POST['admin_action'] ?? '')==='check') {
            if(!$adminGateway || !$adminSettings) throw new RuntimeException('El medio de pago no está disponible.');
            if(time()-(int)($_SESSION['shop_admin_check'] ?? 0)<15) throw new RuntimeException('Esperá 15 segundos entre consultas.');
            $_SESSION['shop_admin_check']=time();
            $order=$adminStore->get(is_string($_POST['order_id'] ?? null)?$_POST['order_id']:'');
            if(!$order || $order['live']!==($adminSettings['environment']==='production')) throw new RuntimeException('La compra pertenece a otro ambiente o no está disponible.');
            $adminStore->refresh($order['id'],$adminGateway,$adminMerchant);
            $adminMessage='Pago consultado en Ualá. La entrega la procesa automáticamente el VPS.';
        } else throw new InvalidArgumentException('Acción inválida.');
    }
} catch(Throwable $exception) {
    $adminError=true;
    $adminMessage=$exception instanceof InvalidArgumentException?$exception->getMessage():'No pudimos completar la operación. Recargá el panel y revisá la conexión y los archivos privados.';
    if(in_array($exception->getMessage(),['La configuración cambió en otra ventana. Recargá antes de guardar.','La sesión venció. Recargá la página.','Esperá 15 segundos entre consultas.','La compra pertenece a otro ambiente o no está disponible.'],true)) $adminMessage=$exception->getMessage();
}
if($adminStore) { try { $adminOrders=$adminStore->administration($adminFilters,$adminPage); } catch(Throwable $ignored) { $adminMessage='No se pudo leer el registro de compras. Revisá los archivos privados.'; $adminError=true; } }
$workerFresh=($worker['last_seen'] ?? 0)>=time()-180; $workerOkay=$workerFresh && in_array($worker['phase'] ?? '',['ok','polling'],true) && empty($worker['last_error']);
$workerLabel=$workerOkay?'Entrega conectada':($workerFresh?'Revisar entrega':'Sin conexión reciente');
$vipModule=defined('__PATH_MODULES_USERCP__') && is_file(__PATH_MODULES_USERCP__.'vip.php');
$vipData=null;
try { $rows=Connection::Database('MuOnline')->query_fetch('SELECT AccountLevel,AccountExpireDate FROM dbo.MEMB_INFO WHERE memb___id = ?', ['panic']); $vipData=$rows[0] ?? null; } catch(Throwable $ignored) {}
$adminUrl=__BASE_URL__.'usercp/shopadmin/';
?>
<section class="recharge-shop shop-management shop-management--v6" aria-labelledby="shop-admin-title">
<header class="recharge-hero"><span class="eyebrow">MU PANIC / ADMINISTRACIÓN</span><h2 id="shop-admin-title">Tu tienda.<br><em>Bajo control.</em></h2><p>Gestioná las recargas, las monturas y tu único plan VIP.</p><div class="shop-admin-badges"><span>Acceso exclusivo: panic</span><span>Ualá · <?php echo panicAccountEscape($adminSettings['environment'] ?? 'Sin configurar'); ?></span><a href="<?php echo panicAccountEscape(__BASE_URL__.'usercp/recharge/'); ?>">Ver tienda →</a></div></header>
<?php if($adminMessage) { ?><div class="recharge-notice<?php echo $adminError?' shop-error':''; ?>" role="status"><?php echo panicAccountEscape($adminMessage); ?></div><?php } ?>
<nav class="recharge-sections" aria-label="Administración de tienda"><a href="#shop-catalogue">Packs de Eryns</a><a href="#shop-mounts">Monturas</a><a href="#shop-vip">VIP único</a><a href="#shop-orders">Compras</a><a href="#shop-delivery">Entrega</a></nav>
<section id="shop-catalogue" class="recharge-section"><div class="recharge-section-head"><div><span class="eyebrow">01 / PACKS Y REGALOS</span><h3>Paquetes y promociones</h3></div><span>$1 ARS = 1 Eryns base</span></div><p>Base = precio en pesos. Base + regalo = monedas acreditadas en el juego.</p><p class="recharge-subtle">Para cambiar el orden, editá la posición. Ocultar un paquete no altera compras existentes. Máximo 12 paquetes y 1.000.000 de monedas por compra.</p>
<?php if(($worker['version'] ?? 0)<2 || !$workerFresh) { ?><div class="recharge-notice">Los bonos quedan preparados, pero solo se ofrecen cuando el VPS informa la versión 2 y tiene una conexión reciente. Así se evitan compras que el servicio anterior no puede entregar.</div><?php } ?>
<form method="post" action="<?php echo panicAccountEscape($adminUrl.'#shop-catalogue'); ?>" class="shop-admin-catalogue"><input type="hidden" name="admin_csrf" value="<?php echo $_SESSION['shop_admin_csrf']; ?>"><input type="hidden" name="revision" value="<?php echo $adminCatalogue['revision']; ?>">
<?php $editRows=$adminCatalogue['packages']; if(count($editRows)<12) $editRows[]=['id'=>'','title'=>'','coins'=>0,'bonus'=>0,'enabled'=>false,'featured'=>false,'starts_at'=>'','ends_at'=>'']; foreach($editRows as $index=>$package) { ?><details class="shop-package-fold"><summary><?php echo $package['id']===''?'Agregar un paquete':number_format($package['coins']+$package['bonus'],0,',','.').' Eryns · $ '.number_format($package['coins'],0,',','.').' ARS'; ?><span><?php echo $package['enabled']?'Visible':'Oculto'; ?> · Editar</span></summary><fieldset class="shop-package-editor"><legend><?php echo $package['id']===''?'Agregar un paquete':'Paquete '.($index+1); ?></legend><div class="shop-editor-grid"><label>Código interno · conservá el existente<input name="packages[<?php echo $index; ?>][id]" value="<?php echo panicAccountEscape($package['id']); ?>" pattern="[a-z0-9_-]{1,40}" maxlength="40" placeholder="wcoin-50000"></label><label>Nombre<input name="packages[<?php echo $index; ?>][title]" value="<?php echo panicAccountEscape($package['title']); ?>" maxlength="120" placeholder="50.000 Eryns"></label><label>Eryns base · también define el precio ARS<input type="number" name="packages[<?php echo $index; ?>][coins]" value="<?php echo $package['coins']; ?>" min="0" max="1000000" step="1"></label><label>Eryns de regalo<input type="number" name="packages[<?php echo $index; ?>][bonus]" value="<?php echo $package['bonus']; ?>" min="0" max="1000000" step="1"></label><label>Inicio del bono (ARG)<input type="datetime-local" name="packages[<?php echo $index; ?>][starts_at]" value="<?php echo $package['starts_at']!==''?panicAccountEscape(panicRechargeArgDate($package['starts_at'],'Y-m-d\TH:i')):''; ?>"></label><label>Fin del bono (ARG)<input type="datetime-local" name="packages[<?php echo $index; ?>][ends_at]" value="<?php echo $package['ends_at']!==''?panicAccountEscape(panicRechargeArgDate($package['ends_at'],'Y-m-d\TH:i')):''; ?>"></label><label>Posición<input type="number" name="packages[<?php echo $index; ?>][position]" value="<?php echo $index+1; ?>" min="1" max="12" step="1"></label><div class="shop-editor-switches"><label><input type="checkbox" name="packages[<?php echo $index; ?>][enabled]" <?php if($package['enabled']) echo 'checked'; ?>> Visible en la tienda</label><label><input type="checkbox" name="packages[<?php echo $index; ?>][featured]" <?php if($package['featured']) echo 'checked'; ?>> Destacar paquete</label></div></div></fieldset></details><?php } ?><button class="recharge-button" name="admin_action" value="catalogue">Guardar catálogo y promociones</button><?php if($adminCatalogue['updated_at']) { ?><p class="recharge-subtle">Último cambio: <?php echo panicAccountEscape(panicRechargeArgDate($adminCatalogue['updated_at'])); ?> ARG</p><?php } ?></form></section>
<?php require __DIR__.'/recharge-admin-storefront.php'; ?>
<section id="shop-orders" class="recharge-section">
<div class="recharge-section-head"><div><span class="eyebrow">04 / CADA COMPRA CUENTA</span><h3>Compras del servidor</h3></div></div>
<form method="get" action="<?php echo panicAccountEscape($adminUrl); ?>" class="shop-admin-filters"><label>Cuenta o número de compra<input name="buscar" value="<?php echo panicAccountEscape($adminFilters['query']); ?>" maxlength="120" placeholder="panic, louismk, PANIC-…"></label><label>Estado<select name="estado"><option value="">Todos los estados</option><?php foreach(['pending'=>'Esperando pago','approved'=>'Entrega pendiente','credited'=>'Eryns acreditados','review'=>'En revisión','creating'=>'Creación pendiente','rejected'=>'No aprobado'] as $key=>$label) { ?><option value="<?php echo $key; ?>" <?php if($adminFilters['state']===$key) echo 'selected'; ?>><?php echo $label; ?></option><?php } ?></select></label><label>Ambiente<select name="ambiente"><?php foreach(['test'=>'Pruebas','production'=>'Producción','all'=>'Todos'] as $key=>$label) { ?><option value="<?php echo $key; ?>" <?php if($adminFilters['environment']===$key) echo 'selected'; ?>><?php echo $label; ?></option><?php } ?></select></label><button class="recharge-button" type="submit">Filtrar</button></form>
<div class="shop-admin-metrics"><?php foreach([['Compras',$adminOrders['summary']['total']],['Pagos aprobados','$ '.number_format($adminOrders['summary']['approved_cents']/100,0,',','.')],['Eryns entregados',number_format($adminOrders['summary']['delivered_coins'],0,',','.')],['Entregas pendientes',$adminOrders['summary']['pending']],['Para revisar',$adminOrders['summary']['review']]] as $metric) { ?><div><span><?php echo $metric[0]; ?></span><strong><?php echo $metric[1]; ?></strong></div><?php } ?></div><p class="recharge-subtle">Totales del filtro. Los pagos de prueba se muestran separados de los de producción.</p>
<?php if(!$adminOrders['orders']) { ?><div class="recharge-history-empty"><strong>No hay compras con estos filtros</strong><p>Probá buscar otra cuenta o seleccionar todos los estados.</p></div><?php } ?>
<div class="recharge-history-list"><?php foreach($adminOrders['orders'] as $order) { [$tone,$label,$copy]=panicRechargeStatus($order); ?><article class="recharge-order" data-order-state="<?php echo $tone; ?>"><div class="recharge-order-top"><span><?php echo panicAccountEscape(panicRechargeArgDate($order['created_at'])); ?> ARG · <?php echo $order['live']?'Producción':'Prueba'; ?></span><span class="recharge-status"><?php echo panicAccountEscape($label); ?></span></div><div class="recharge-order-value"><strong><?php echo panicAccountEscape($order['account']); ?><small> <?php echo number_format($order['coins'],0,',','.'); ?> Eryns</small></strong><b>$ <?php echo number_format($order['price_cents']/100,0,',','.'); ?> ARS</b></div><p><?php echo panicAccountEscape($copy); ?></p><details><summary>Detalle de compra y entrega</summary><ul><?php foreach($order['lines'] as $line) { ?><li><?php echo $line['quantity']; ?> × <?php echo panicAccountEscape(panicAccountCurrencyLabel($line['title'])); ?><?php if($line['bonus']>0) { ?> · <?php echo number_format($line['bonus'],0,',','.'); ?> de bono por paquete<?php } ?></li><?php } ?></ul><p class="recharge-order-reference"><?php echo $order['id']; ?><br>Pago: <?php echo panicAccountEscape($order['payment_id'] ?? 'Sin confirmar'); ?></p><?php if(isset($order['before_coin'],$order['after_coin'])) { ?><p>Saldo: <?php echo number_format($order['before_coin'],0,',','.'); ?> → <?php echo number_format($order['after_coin'],0,',','.'); ?> Eryns<br>Entrega: <?php echo panicAccountEscape(panicRechargeArgDate($order['credited_at'])); ?> ARG</p><?php } ?><?php if($order['checked_at']) { ?><p>Última consulta: <?php echo panicAccountEscape(panicRechargeArgDate($order['checked_at'])); ?> ARG</p><?php } ?><?php if($order['error'] || $order['check_error']) { ?><p class="shop-error">Comprobación pendiente: <?php echo panicAccountEscape($order['check_error'] ?? $order['error']); ?></p><?php } ?></details><?php if($adminGateway && $order['payment_id'] && $order['live']===($adminSettings['environment']==='production')) { ?><form method="post" action="<?php echo panicAccountEscape($adminUrl.'?'.http_build_query(['buscar'=>$adminFilters['query'],'estado'=>$adminFilters['state'],'ambiente'=>$adminFilters['environment'],'pagina'=>$adminPage]).'#shop-orders'); ?>"><input type="hidden" name="admin_csrf" value="<?php echo $_SESSION['shop_admin_csrf']; ?>"><input type="hidden" name="order_id" value="<?php echo $order['id']; ?>"><button class="recharge-text-button" name="admin_action" value="check">Consultar pago en Ualá</button></form><?php } ?></article><?php } ?></div>
<?php if($adminOrders['total']>20) { ?><nav class="recharge-pagination" aria-label="Páginas de compras del servidor"><?php foreach([-1=>'← Anteriores',1=>'Siguientes →'] as $delta=>$label) { $target=$adminPage+$delta; if($target<1 || ($target-1)*20>=$adminOrders['total']) continue; ?><a href="<?php echo panicAccountEscape('?'.http_build_query(['buscar'=>$adminFilters['query'],'estado'=>$adminFilters['state'],'ambiente'=>$adminFilters['environment'],'pagina'=>$target]).'#shop-orders'); ?>"><?php echo $label; ?></a><?php } ?><span>Página <?php echo $adminPage; ?> de <?php echo ceil($adminOrders['total']/20); ?></span></nav><?php } ?>
</section>
<section id="shop-delivery" class="recharge-section"><div class="recharge-section-head"><div><span class="eyebrow">05 / DE LA WEB AL JUEGO</span><h3>Entrega automática</h3></div><span class="recharge-status"><?php echo $workerLabel; ?></span></div><div class="shop-admin-metrics"><div><span>Último contacto del VPS</span><strong><?php echo isset($worker['last_seen'])?panicAccountEscape(panicRechargeArgDate('@'.$worker['last_seen'],'H:i:s')):'Sin registro'; ?></strong></div><div><span>Versión del servicio</span><strong><?php echo (int)($worker['version'] ?? 0); ?></strong></div><div><span>Esperando desconexión</span><strong><?php echo (int)($worker['waiting'] ?? 0); ?></strong></div><div><span>Consultas de pago con error</span><strong><?php echo (int)($worker['check_errors'] ?? 0); ?></strong></div></div><p>La tarea consulta cada minuto. Las cuentas conectadas esperan a desconectarse. Cada entrega queda registrada para que los reintentos no dupliquen monedas.</p><?php if(!empty($worker['last_error'])) { ?><p class="shop-error">El VPS informó un error. Revisá su registro con la opción -Status del sincronizador.</p><?php } ?><a class="recharge-text-button" href="<?php echo panicAccountEscape($adminUrl.'#shop-delivery'); ?>">Actualizar panel</a></section>

<details class="shop-system-details"><summary>Diagnóstico VIP del juego</summary><section id="shop-vip-diagnostic" class="recharge-section"><div class="recharge-section-head"><div><span class="eyebrow">04 / MEMBRESÍAS</span><h3>VIP del servidor</h3></div><span class="recharge-status">Revisión de integración</span></div><p>La base activa ya tiene nivel y vencimiento de VIP. El panel gestiona la presentación de una única membresía; la activación y renovación se conservan en el juego.</p><div class="shop-vip-grid"><article><h4>VIP de la cuenta panic</h4><?php if($vipData) { ?><p>Nivel actual: <b><?php echo (int)$vipData['AccountLevel']; ?></b><br>Vencimiento registrado: <b><?php echo panicAccountEscape($vipData['AccountExpireDate']); ?></b></p><?php } else { ?><p>No se pudo consultar el nivel de esta cuenta.</p><?php } ?><p>Consulta de lectura. No cambia la membresía.</p></article><article><h4>Compra desde el juego</h4><p>El servicio del VPS enviará una lectura de los parámetros VIP disponibles en su configuración.</p><?php if(!empty($worker['vip_config'])) { ?><details><summary>Ver configuración detectada</summary><dl><?php foreach($worker['vip_config'] as $key=>$value) { ?><dt><?php echo panicAccountEscape($key); ?></dt><dd><?php echo panicAccountEscape($value); ?></dd><?php } ?></dl></details><?php } else { ?><p class="recharge-subtle">Todavía no hay parámetros confirmados.</p><?php } ?></article><article><h4>Módulo VIP de la web</h4><p><?php echo $vipModule?'Hay un módulo VIP instalado. Se conserva su funcionamiento actual.':'No se detectó el archivo del módulo VIP estándar. Puede existir una integración adicional.'; ?></p><?php if($vipModule) { ?><a class="recharge-text-button" href="<?php echo panicAccountEscape(__BASE_URL__.'usercp/vip/'); ?>">Abrir VIP actual →</a><?php } ?><p>La venta directa de VIP no está habilitada por este panel todavía.</p></article></div></section></details></section>

<script src="<?php echo __PATH_TEMPLATE__; ?>js/recharge-admin.js?v=<?php echo substr(hash_file('sha256',__DIR__.'/../js/recharge-admin.js'),0,12); ?>"></script>
