<?php if(!defined('access') || !access) die(); ?>
<form method="post" action="<?php echo panicAccountEscape($adminUrl.'#shop-vip'); ?>" class="shop-presentation-form">
<input type="hidden" name="admin_csrf" value="<?php echo panicAccountEscape($_SESSION['shop_admin_csrf']); ?>"><input type="hidden" name="storefront_revision" value="<?php echo $adminStorefront['revision']; ?>">
<section id="shop-mounts" class="recharge-section"><div class="recharge-section-head"><div><span class="eyebrow">02 / VITRINA MANUAL</span><h3>Las tres monturas</h3></div><span>Precios en Eryns</span></div><p>Copiá los precios de X. Guardar acá actualiza la web; no cambia el juego.</p><div class="shop-mount-editors">
<?php foreach($adminStorefront['products'] as $product) { $slug=$product['slug']; ?><article class="shop-mount-editor"><img src="<?php echo __PATH_TEMPLATE__; ?>img/recharge/<?php echo $slug; ?>-scene-v5.webp" alt="" width="810" height="1080" loading="lazy"><h4><?php echo ucfirst($slug); ?></h4><label>Precio normal<input type="number" min="1" max="1000000" step="1" name="products[<?php echo $slug; ?>][price_coins]" value="<?php echo $product['price_coins'] ?? ''; ?>" placeholder="Pendiente"></label><label>Precio VIP mostrado en X<input type="number" min="1" max="1000000" step="1" name="products[<?php echo $slug; ?>][vip_price_coins]" value="<?php echo $product['vip_price_coins'] ?? ''; ?>" placeholder="Pendiente"></label><label class="shop-inline-switch"><input type="checkbox" name="products[<?php echo $slug; ?>][available]" <?php if($product['available']) echo 'checked'; ?>> Habilitar objetivo de recarga</label></article><?php } ?>
</div><p class="recharge-subtle">El precio VIP se carga tal como aparece en X para respetar su redondeo. Campos vacíos: pendiente. Con el objetivo deshabilitado, la montura sigue sellada.</p></section>
<section id="shop-vip" class="recharge-section"><div class="recharge-section-head"><div><span class="eyebrow">03 / UNA MEMBRESÍA PARA RENOVAR</span><h3>Un solo VIP</h3></div><span>Presentación en la web</span></div><p>Definí una oferta clara y sus beneficios. La activación y la renovación siguen dentro del juego.</p><div class="shop-vip-editor-top"><img src="<?php echo __PATH_TEMPLATE__; ?>img/recharge/vip-insignia-v5.svg" alt="VIP" width="100" height="80"><div class="shop-editor-grid"><label>Nombre de la membresía<input name="vip[name]" value="<?php echo panicAccountEscape($adminStorefront['vip']['name']); ?>" maxlength="80" required></label><label>Duración en días<input type="number" name="vip[days]" value="<?php echo $adminStorefront['vip']['days'] ?? ''; ?>" min="1" max="3650" step="1" placeholder="Pendiente"></label><label>Precio en Eryns<input type="number" name="vip[price_coins]" value="<?php echo $adminStorefront['vip']['price_coins'] ?? ''; ?>" min="1" max="1000000" step="1" placeholder="Pendiente"></label></div></div>
<div class="shop-vip-benefit-editors"><?php foreach($adminStorefront['vip']['benefits'] as $index=>$benefit) { ?><details class="shop-benefit-fold" <?php if($benefit['enabled']) echo 'open'; ?>><summary><?php echo $benefit['title']!==''?panicAccountEscape($benefit['title']):'Agregar beneficio '.($index+1); ?><span><?php echo $benefit['enabled']?'Publicado':'Borrador'; ?></span></summary><fieldset><legend>Beneficio <?php echo $index+1; ?></legend><label>Título corto<input name="vip[benefits][<?php echo $index; ?>][title]" value="<?php echo panicAccountEscape($benefit['title']); ?>" maxlength="80" placeholder="Por definir"></label><label>Detalle real del beneficio<textarea name="vip[benefits][<?php echo $index; ?>][detail]" maxlength="1200" rows="3" placeholder="Completá valores y condiciones antes de publicarlo"><?php echo panicAccountEscape($benefit['detail']); ?></textarea></label><label class="shop-inline-switch"><input type="checkbox" name="vip[benefits][<?php echo $index; ?>][enabled]" <?php if($benefit['enabled']) echo 'checked'; ?>> Mostrar en la tienda</label></fieldset></details><?php } ?></div>
<p class="recharge-subtle">EXP y drop quedan como borradores hasta que confirmes los valores. El descuento del 10% en X ya está publicado. Este panel no crea niveles VIP ni cobros recurrentes automáticos.</p>
<div class="shop-presentation-save"><button type="submit" class="recharge-button" name="admin_action" value="storefront">Guardar monturas y VIP</button><span><?php echo $adminStorefront['updated_at']?'Último cambio: '.panicAccountEscape(panicRechargeArgDate($adminStorefront['updated_at'])):'Todavía sin cambios guardados'; ?></span></div>
</section></form>
