<?php if(!defined('access') || !access) die(); $vipBenefits=array_values(array_filter($shopVipOffer['benefits'],function($benefit) { return $benefit['enabled']; })); ?>
<section class="eryns-vip-salon eryns-vip-salon--single eryns-motion-surface" id="eryns-vip" aria-labelledby="eryns-vip-title">
  <div class="eryns-vip-heading"><span class="eryns-overline">UNA SOLA MEMBRESÍA</span><h3 id="eryns-vip-title">Más PANIC. Con tu VIP.</h3><p>Tu próximo capítulo merece una presencia propia.</p></div>
  <div class="eryns-vip-layout">
    <figure class="eryns-vip-portrait"><img src="<?php echo __PATH_TEMPLATE__; ?>img/recharge/vip-champion-scene-v5.webp" alt="Concepto de un caballero de MU con armadura y aura doradas" width="810" height="1080" loading="lazy" decoding="async"><div class="eryns-vip-nameplate"><img src="<?php echo __PATH_TEMPLATE__; ?>img/recharge/vip-insignia-v5.svg" alt="VIP" width="78" height="64"><strong><?php echo panicAccountEscape($rechargeAccount); ?></strong></div><figcaption>Vista conceptual de la identidad VIP</figcaption><span class="eryns-vip-dust" aria-hidden="true"></span></figure>
    <div class="eryns-vip-content">
      <div class="eryns-vip-state" data-vip-state="<?php echo $shopVip===null?'unknown':($shopVip['active']?'active':'normal'); ?>"><?php if($shopVip===null) { ?><span>ESTADO DE TU CUENTA</span><strong>No disponible</strong><?php } elseif($shopVip['active']) { ?><span>✦ VIP ACTIVO</span><strong><?php echo $shopVip['days']; ?> días restantes</strong><?php } else { ?><span>TU CUENTA</span><strong>Cuenta normal</strong><?php } ?></div>
      <div class="eryns-vip-single-plan"><span>EL VIP DE MU PANIC</span><h4><?php echo panicAccountEscape($shopVipOffer['name']); ?></h4><p>Una membresía. Todos sus beneficios.</p><div class="eryns-vip-plan-price"><strong><?php echo $shopVipOffer['price_coins']===null?'[COMPLETAR]':number_format($shopVipOffer['price_coins'],0,',','.'); ?></strong><span>Eryns / <?php echo $shopVipOffer['days']===null?'[COMPLETAR]':$shopVipOffer['days']; ?> días</span></div></div>
      <div class="eryns-vip-benefits eryns-vip-benefits--single"><?php foreach($vipBenefits as $i=>$benefit) { $icon=['crown','shield','star'][$i%3]; ?><details><summary><img src="<?php echo __PATH_TEMPLATE__; ?>img/recharge/vip-benefit-<?php echo $icon; ?>-v5.svg" width="58" height="58" alt=""><strong><?php echo panicAccountEscape($benefit['title']); ?></strong><span>Ver beneficio +</span></summary><p><?php echo panicAccountEscape($benefit['detail']); ?></p></details><?php } ?></div>
      <?php if(count($vipBenefits)<2) { ?><p class="eryns-vip-upcoming-benefits">Más beneficios por definir.</p><?php } ?>
      <button type="button" class="eryns-vip-cta" data-vip-cta aria-controls="eryns-vip-plan-details" aria-expanded="false"><?php echo $shopVip===null?'Conocé el VIP':($shopVip['active']?'Extender VIP':'Activá tu VIP'); ?> <span aria-hidden="true">→</span></button>
      <p class="eryns-vip-renewal-note">Activación y renovación dentro del juego.</p>
      <details id="eryns-vip-plan-details" class="eryns-vip-plan-details"><summary>Cómo activar o renovar</summary><p>La membresía se compra dentro del juego. La web acredita Eryns; todavía no activa ni extiende VIP.</p><?php if($shopVipOffer['price_coins']===null || $shopVipOffer['days']===null) { ?><p>[COMPLETAR] · Precio, duración y condiciones del plan.</p><?php } else { ?><p><?php echo panicAccountEscape($shopVipOffer['name']); ?> · <?php echo $shopVipOffer['days']; ?> días · <?php echo number_format($shopVipOffer['price_coins'],0,',','.'); ?> Eryns. Revisá estos valores en el juego antes de comprar.</p><?php } ?></details>
    </div>
  </div>
</section>
