<?php if(!defined('access') || !access) die(); ?>
<section class="eryns-vip-salon eryns-motion-surface" id="eryns-vip" aria-labelledby="eryns-vip-title">
  <div class="eryns-vip-heading"><span class="eryns-overline">EL SALÓN PRIVADO</span><h3 id="eryns-vip-title">Tu nombre. Otra presencia.</h3><p>Conocé la próxima experiencia VIP de PANIC.</p></div>
  <div class="eryns-vip-layout">
    <figure class="eryns-vip-portrait"><img src="<?php echo __PATH_TEMPLATE__; ?>img/recharge/vip-champion-scene-v5.webp" alt="Concepto de un caballero de MU en un salón oscuro, con armadura y aura doradas" width="810" height="1080" loading="lazy" decoding="async"><div class="eryns-vip-nameplate"><img src="<?php echo __PATH_TEMPLATE__; ?>img/recharge/vip-insignia-v5.svg" alt="VIP" width="78" height="64"><strong><?php echo panicAccountEscape($rechargeAccount); ?></strong></div><figcaption>Vista conceptual de la identidad VIP</figcaption><span class="eryns-vip-dust" aria-hidden="true"></span></figure>
    <div class="eryns-vip-content">
      <div class="eryns-vip-state" data-vip-state="<?php echo $shopVip===null?'unknown':($shopVip['active']?'active':'normal'); ?>"><?php if($shopVip===null) { ?><span>ESTADO DE TU CUENTA</span><strong>No disponible</strong><?php } elseif($shopVip['active']) { ?><span>✦ VIP ACTIVO</span><strong><?php echo $shopVip['days']; ?> días restantes</strong><?php } else { ?><span>TU CUENTA</span><strong>Cuenta normal</strong><?php } ?></div>
      <div class="eryns-vip-comparison" aria-label="Comparación Normal y VIP; beneficios pendientes de definición"><div class="eryns-vip-normal"><span>NORMAL</span><img src="<?php echo __PATH_TEMPLATE__; ?>img/recharge/vip-benefit-crown-v5.svg" width="54" height="54" alt=""><strong>Tu camino actual</strong><small>[COMPLETAR]</small></div><div class="eryns-vip-exclusive"><span>VIP</span><img src="<?php echo __PATH_TEMPLATE__; ?>img/recharge/vip-benefit-crown-v5.svg" width="54" height="54" alt=""><strong>Tu próximo capítulo</strong><small>[COMPLETAR]</small></div></div>
      <div class="eryns-vip-benefits"><?php foreach(['crown','shield','star'] as $icon) { ?><details><summary><img src="<?php echo __PATH_TEMPLATE__; ?>img/recharge/vip-benefit-<?php echo $icon; ?>-v5.svg" width="58" height="58" alt=""><strong>[COMPLETAR]</strong><span>Ver beneficio +</span></summary><p>[COMPLETAR] · Descripción y condiciones del beneficio.</p></details><?php } ?></div>
      <div class="eryns-vip-duration-heading"><span>ELEGÍ TU ESTADÍA</span><small>Duraciones y precios por definir</small></div>
      <div class="eryns-vip-durations" role="group" aria-label="Vista previa de planes VIP; no disponibles para comprar"><?php for($vipSlot=0;$vipSlot<3;$vipSlot++) { ?><button type="button" data-vip-duration="<?php echo $vipSlot; ?>" class="eryns-vip-duration<?php echo $vipSlot===1?' is-featured':''; ?>" aria-pressed="<?php echo $vipSlot===1?'true':'false'; ?>"><span><?php echo $vipSlot===1?'DESTACADO':'VIP'; ?></span><strong>[COMPLETAR]</strong><small>días</small><b>[COMPLETAR] Eryns</b></button><?php } ?></div>
      <button type="button" class="eryns-vip-cta" data-vip-cta aria-controls="eryns-vip-plan-details" aria-expanded="false"><?php echo $shopVip===null?'Conocé el VIP':($shopVip['active']?'Extender VIP':'Activá tu VIP'); ?> <span aria-hidden="true">→</span></button>
      <details id="eryns-vip-plan-details" class="eryns-vip-plan-details"><summary>Detalles de activación</summary><p>[COMPLETAR] · Beneficios, duración, precio y condiciones. La compra de estos planes se habilitará cuando estén definidos.</p></details>
    </div>
  </div>
</section>
