<?php
if(!defined('access') || !access) die();
if(!isLoggedIn()) return;
require_once __DIR__.'/recharge-domain.php';
require_once __DIR__.'/recharge-wallet.php';
require_once __DIR__.'/recharge-management.php';
$rechargeConfig=require __DIR__.'/recharge-config.php';
$rechargeAccount=(string)($_SESSION['username'] ?? '');
$rechargeBalance=panicRechargeWalletBalance($rechargeAccount);
$rechargePackages=[];
try { $publicOffers=(new PanicRechargeManagement())->offers(); } catch(Throwable $ignored) { $publicOffers=[]; }
foreach($publicOffers as $package) {
    try { $rechargePackages[]=PanicRecharge::package($package); } catch(InvalidArgumentException $ignored) {}
}
require __DIR__.'/recharge-shop-controller.php';
if(!$rechargePackages) $shopCanBuy=false;
// Editorial highlight only. Offers, prices and bonuses remain controlled by the shop.
$shopHasFeatured=false;
foreach($rechargePackages as $package) if(!empty($package['featured'])) $shopHasFeatured=true;
$shopSpotlightIndex=(int)floor(count($rechargePackages)/2);

$shopFeaturedIndex=$shopSpotlightIndex;
foreach($rechargePackages as $i=>$package) if(!empty($package['featured'])) { $shopFeaturedIndex=$i; break; }
$shopInitialQuantities=$shopQuantities;
if(!$shopInitialQuantities && isset($rechargePackages[$shopFeaturedIndex])) $shopInitialQuantities[$rechargePackages[$shopFeaturedIndex]['id']]='1';
$shopLore=json_decode(file_get_contents(__DIR__.'/atlas-vinculos.json'),true);
$shopCreatures=[]; foreach(($shopLore['entries'] ?? []) as $creature) $shopCreatures[$creature['slug']]=$creature;
$shopExhibits=[
 ['slug'=>'theryon','tab'=>'Monturas','kicker'=>'LAS TRES BESTIAS PRIMORDIALES','title'=>'Que te vean llegar.','copy'=>'El rugido de Theryon. Las alas de Nerathys. El cielo carmesí de Vaeraxes. Elegí la historia que querés llevar a la batalla.'],
 ['slug'=>'aurion','tab'=>'El Pacto','kicker'=>'UN COMPAÑERO. UN CAMINO.','title'=>'Tu historia tiene compañía.','copy'=>'Desde tu primer vínculo hasta su despertar. Conocé los linajes del Pacto de los Ocho y los materiales de cada evolución.'],
 ['slug'=>'aurethia','tab'=>'Exclusivos','kicker'=>'LOS CUSTODIOS DEL ECLIPSE','title'=>'Una presencia que se recuerda.','copy'=>'Vaelkar y Aurethia guardan un mismo juramento. Descubrí sus historias y elegí qué guardián querés a tu lado.']
];
?>
<section class="recharge-shop eryns-store" aria-labelledby="recharge-title" data-recharge-shop>
    <div class="eryns-store-top"><a href="<?php echo __BASE_URL__; ?>usercp/">← Mi cuenta</a><span>MU PANIC <b>/</b> ERYNS</span><a href="#recharge-history">Mis compras</a></div>
    <?php if(!$shopCanBuy) { ?><div class="recharge-notice"><strong>Armá tu próxima recarga</strong><p>Podés probar el selector y comparar cantidades. El pago se habilitará cuando esté listo el servicio de recargas.</p></div><?php } ?>
    <?php if($shopMessage || $shopCreated) { ?><div id="recharge-checkout" class="eryns-checkout-feedback">
    <?php if($shopMessage) { ?><div class="recharge-notice recharge-feedback" role="status"><strong><?php echo panicAccountEscape($shopMessage); ?></strong></div><?php } ?>
    <?php if($shopCreated && isset($shopCreated['checkout_url']) && $shopCreated['payment_state']==='pending') { ?>
    <div class="recharge-ready"><span class="eyebrow">TU COMPRA ESTÁ LISTA</span><h3><?php echo number_format($shopCreated['coins'],0,',','.'); ?> Eryns para <?php echo panicAccountEscape($shopCreated['account']); ?></h3><p>Total: <b>$ <?php echo number_format($shopCreated['price_cents']/100,0,',','.'); ?> ARS</b>. Revisá que Ualá muestre este mismo importe antes de pagar.</p><a class="recharge-button" href="<?php echo panicAccountEscape($shopCreated['checkout_url']); ?>" target="_blank" rel="noopener noreferrer">Continuar a Ualá ↗</a><p class="recharge-subtle">Tu compra ya está guardada en el historial.</p></div>
    <?php } ?>
    </div><?php } ?>
    <?php if($shopAdmin) { ?><p><a class="recharge-button recharge-button-secondary" href="<?php echo panicAccountEscape(__BASE_URL__.'usercp/shopadmin/'); ?>">Administrar tienda →</a></p><?php } ?>

    <header class="eryns-stage">
        <div class="eryns-stage-copy"><span class="eryns-overline">TU HISTORIA EN PANIC</span><h2 id="recharge-title">Lo próximo<br>puede ser<br><em>legendario.</em></h2><p>El compañero. La montura. Ese próximo objetivo.<br>Todo empieza con lo que vos elegís.</p><a href="#recharge-packages" class="eryns-stage-cta">Elegí tu recarga <span aria-hidden="true">↓</span></a></div>
        <span class="eryns-stage-signature">VÍNCULOS / BESTIAS / LEYENDAS</span>
    </header>
    <section id="recharge-packages" class="eryns-buy" aria-labelledby="eryns-buy-title">
      <form method="post" action="<?php echo panicAccountEscape(__BASE_URL__.'usercp/recharge/#recharge-checkout'); ?>" data-cart-form>
        <input type="hidden" name="recharge_csrf" value="<?php echo panicAccountEscape($_SESSION['recharge_csrf']); ?>">
        <input type="hidden" name="recharge_nonce" value="<?php echo panicAccountEscape($_SESSION['recharge_nonce']); ?>">
        <input type="hidden" name="recharge_action" value="create">
        <div class="eryns-buy-heading"><div><span class="eryns-overline">LA MONEDA DE PANIC</span><h3 id="eryns-buy-title">Elegí tus Eryns.</h3></div><p>Cuenta <b><?php echo panicAccountEscape($rechargeAccount); ?></b><br>Tu saldo: <b><?php echo $rechargeBalance===null?'No disponible':number_format($rechargeBalance,0,',','.').' Eryns'; ?></b></p></div>
        <div class="eryns-denominations" role="group" aria-label="Elegí una recarga"><?php foreach($rechargePackages as $i=>$package) { ?><button type="button" class="eryns-denomination<?php echo $i===$shopFeaturedIndex?' eryns-denomination--featured':''; ?>" data-choose-package="<?php echo panicAccountEscape($package['id']); ?>" aria-pressed="false"><?php if($i===$shopFeaturedIndex) { ?><span>DESTACADO</span><?php } ?><strong><?php echo number_format($package['coins']+$package['bonus'],0,',','.'); ?></strong><small>Eryns</small><?php if($package['bonus']>0) { ?><b>+<?php echo number_format($package['bonus'],0,',','.'); ?> extra incluido</b><?php } ?></button><?php } ?></div>
        <div id="recharge-cart" class="eryns-purchase" aria-labelledby="cart-title"><div class="eryns-purchase-amount"><span id="cart-title">VAN A TU CUENTA</span><strong data-total-coins>0 Eryns</strong><p data-cart-hint>Elegí tu recarga.</p></div><div class="eryns-purchase-action"><span>TOTAL EN PESOS ARGENTINOS</span><strong data-total-price>$ 0 ARS</strong><button class="recharge-button" type="submit" data-cart-submit data-enabled="<?php echo $shopCanBuy?'1':'0'; ?>" <?php if(!$shopCanBuy) echo 'disabled'; ?>><?php echo $shopCanBuy?'Preparar pago con Ualá':'Pagos próximamente'; ?></button><small>El siguiente paso prepara tu enlace de pago.</small></div></div>
        <details class="eryns-combine"><summary>¿Querés otra cantidad? Combiná paquetes</summary><div class="eryns-quantity-list"><?php foreach($rechargePackages as $package) { ?><div class="eryns-quantity-row" data-package data-coins="<?php echo $package['coins']+$package['bonus']; ?>" data-price="<?php echo $package['price_cents']; ?>" data-title="<?php echo panicAccountEscape(panicAccountCurrencyLabel($package['title'])); ?>"><div><label for="quantity-<?php echo $package['id']; ?>"><?php echo number_format($package['coins']+$package['bonus'],0,',','.'); ?> Eryns</label><small>$ <?php echo number_format($package['price_cents']/100,0,',','.'); ?> ARS por paquete<?php if($package['bonus']>0) { ?> · <?php echo number_format($package['bonus'],0,',','.'); ?> extra incluido<?php } ?></small><p data-line-total>Sin seleccionar</p></div><div class="eryns-stepper"><button type="button" data-quantity-change="-1" aria-label="Quitar un paquete de <?php echo $package['coins']+$package['bonus']; ?> Eryns">−</button><input id="quantity-<?php echo $package['id']; ?>" name="quantity[<?php echo $package['id']; ?>]" type="number" inputmode="numeric" min="0" max="99" step="1" value="<?php echo panicAccountEscape($shopInitialQuantities[$package['id']] ?? '0'); ?>"><button type="button" data-quantity-change="1" aria-label="Agregar un paquete de <?php echo $package['coins']+$package['bonus']; ?> Eryns">+</button></div></div><?php } ?></div><div data-cart-lines class="eryns-cart-lines"></div><small>Hasta 99 unidades por paquete y $1.000.000 por compra. Los bonos activos se incluyen en el total.</small></details>
        <p class="eryns-terms">Al continuar aceptás los <a href="<?php echo __BASE_URL__; ?>tos/" target="_blank" rel="noopener">Términos</a>, la <a href="<?php echo __BASE_URL__; ?>refunds/" target="_blank" rel="noopener">política de compras y reembolsos</a> y la <a href="<?php echo __BASE_URL__; ?>privacy/" target="_blank" rel="noopener">Privacidad</a>.</p>
        <noscript><p>Escribí las cantidades en «Combiná paquetes». El servidor verificará el importe antes de preparar el enlace.</p></noscript>
      </form>
      <div class="eryns-confidence"><span><b>Ualá</b> Completás el pago en su página</span><span><b>A tu cuenta</b> Saldo compartido entre personajes</span><span><b>Entrega automática</b> Desconectate del juego para recibirla</span></div>
    </section>
    <section class="eryns-discovery" aria-labelledby="eryns-discovery-title"><div class="eryns-discovery-heading"><span class="eryns-overline">EL MOTIVO ES TUYO</span><h3 id="eryns-discovery-title">¿Cuál es tu próximo objetivo?</h3></div><div class="eryns-experience-tabs" role="tablist" aria-label="Descubrí PANIC"><?php foreach($shopExhibits as $i=>$exhibit) { ?><button type="button" role="tab" id="eryns-tab-<?php echo $exhibit['slug']; ?>" aria-controls="eryns-experience-<?php echo $exhibit['slug']; ?>" aria-selected="<?php echo $i===0?'true':'false'; ?>" tabindex="<?php echo $i===0?'0':'-1'; ?>" data-experience-tab="<?php echo $exhibit['slug']; ?>"><?php echo $exhibit['tab']; ?></button><?php } ?></div>
    <?php foreach($shopExhibits as $i=>$exhibit) { $creature=$shopCreatures[$exhibit['slug']]; ?><article class="eryns-experience" role="tabpanel" id="eryns-experience-<?php echo $exhibit['slug']; ?>" aria-labelledby="eryns-tab-<?php echo $exhibit['slug']; ?>" <?php if($i!==0) echo 'hidden'; ?> data-experience="<?php echo $exhibit['slug']; ?>"><div class="eryns-experience-copy"><span class="eryns-overline"><?php echo $exhibit['kicker']; ?></span><h4><?php echo $exhibit['title']; ?></h4><p><?php echo $exhibit['copy']; ?></p><button type="button" class="eryns-preview-button" data-open-creature="eryns-creature-<?php echo $exhibit['slug']; ?>">Ver a <?php echo panicAccountEscape($creature['name']); ?> de cerca <span aria-hidden="true">↗</span></button><a href="#recharge-packages" class="eryns-experience-buy">Elegir mis Eryns <span aria-hidden="true">↑</span></a></div><div class="eryns-experience-art"><img src="<?php echo __PATH_TEMPLATE__.panicAccountEscape($creature['image']); ?>" alt="<?php echo panicAccountEscape($creature['name']); ?>" width="1024" height="1024" loading="lazy"><span><?php echo panicAccountEscape($creature['name']); ?></span></div></article>
    <dialog class="eryns-creature-dialog" id="eryns-creature-<?php echo $exhibit['slug']; ?>" aria-labelledby="eryns-creature-title-<?php echo $exhibit['slug']; ?>"><button type="button" class="eryns-dialog-close" data-close-creature aria-label="Cerrar presentación">×</button><div class="eryns-dialog-grid"><img src="<?php echo __PATH_TEMPLATE__.panicAccountEscape($creature['image']); ?>" alt="<?php echo panicAccountEscape($creature['name']); ?>" width="1024" height="1024" loading="lazy"><div><span class="eryns-overline"><?php echo panicAccountEscape($creature['title']); ?></span><h3 id="eryns-creature-title-<?php echo $exhibit['slug']; ?>"><?php echo panicAccountEscape($creature['name']); ?></h3><p><?php echo panicAccountEscape($creature['role']); ?></p><ul><?php foreach($creature['stats'] as $stat) { ?><li><?php echo panicAccountEscape($stat); ?></li><?php } ?></ul><p class="eryns-availability"><?php echo panicAccountEscape($creature['obtain']); ?>. Precios y disponibilidad: X / F11 → Tienda.</p><button type="button" class="eryns-dialog-buy" data-return-to-buy>Volver a elegir Eryns →</button></div></div></dialog>
    <?php } ?><p class="eryns-discovery-note">Explorá los sistemas de PANIC. Revisá precios y disponibilidad en X / F11 → Tienda antes de recargar. Las mezclas tienen probabilidades de éxito; los materiales no garantizan una evolución.</p></section>
    <div class="eryns-thanks"><span>HECHO PARA SEGUIR JUGANDO.</span><p>Cada recarga ayuda a mantener y desarrollar MU PANIC.<br><b>Gracias por construir este mundo con nosotros.</b></p></div>
    <section id="recharge-history" class="recharge-section">
        <div class="recharge-section-head"><div><span class="eyebrow">02 / SEGUÍ TU RECARGA</span><h3>Mis compras</h3></div><span>Actualización automática de estados</span></div>
        <?php if(!$shopHistory['orders']) { ?><div class="recharge-history-empty"><span class="recharge-gem" aria-hidden="true"><?php echo panicAccountIcon('coin'); ?></span><strong>Acá empieza tu historial</strong><p>Cuando prepares una compra, la vas a encontrar acá con su precio y estado.</p></div><?php } ?>
        <div class="recharge-history-list"><?php foreach($shopHistory['orders'] as $order) { [$tone,$label,$copy]=panicRechargeStatus($order); ?>
            <article class="recharge-order" data-order-id="<?php echo $order['id']; ?>" data-order-state="<?php echo $tone; ?>"><div class="recharge-order-top"><span class="recharge-order-date"><?php echo panicAccountEscape(panicRechargeArgDate($order['created_at'])); ?> ARG</span><span class="recharge-status" data-order-label><?php echo panicAccountEscape($label); ?></span></div><div class="recharge-order-value"><strong><?php echo number_format($order['coins'],0,',','.'); ?> <small>Eryns</small></strong><b>$ <?php echo number_format($order['price_cents']/100,0,',','.'); ?> ARS</b></div><p data-order-copy><?php echo panicAccountEscape($copy); ?></p><div class="recharge-order-actions"><?php if($order['payment_state']==='pending' && isset($order['checkout_url'])) { ?><a class="recharge-button recharge-button-secondary" data-order-pay href="<?php echo panicAccountEscape($order['checkout_url']); ?>" target="_blank" rel="noopener noreferrer">Continuar pago ↗</a><?php } ?><?php if($shopSettings && $order['live']===($shopSettings['environment']==='production') && $order['payment_state']!=='creating') { ?><form method="post" action="<?php echo panicAccountEscape(__BASE_URL__.'usercp/recharge/#recharge-history'); ?>"><input type="hidden" name="recharge_csrf" value="<?php echo panicAccountEscape($_SESSION['recharge_csrf']); ?>"><input type="hidden" name="order_id" value="<?php echo $order['id']; ?>"><button type="submit" name="recharge_action" value="refresh" class="recharge-text-button">Actualizar estado</button></form><?php } ?></div><details><summary>Ver detalle y número de compra</summary><ul><?php foreach($order['lines'] as $line) { ?><li><?php echo $line['quantity']; ?> × <?php echo panicAccountEscape(panicAccountCurrencyLabel($line['title'])); ?></li><?php } ?></ul><p>Cuenta: <b><?php echo panicAccountEscape($order['account']); ?></b><br><span class="recharge-order-reference"><?php echo $order['id']; ?></span></p></details></article>
        <?php } ?></div>
        <?php if($shopHistory['total']>10) { ?><nav class="recharge-pagination" aria-label="Páginas de compras"><?php if($shopPage>1) { ?><a href="?compras=<?php echo $shopPage-1; ?>#recharge-history">← Anteriores</a><?php } ?><span>Página <?php echo $shopPage; ?> de <?php echo (int)ceil($shopHistory['total']/10); ?></span><?php if($shopPage*10<$shopHistory['total']) { ?><a href="?compras=<?php echo $shopPage+1; ?>#recharge-history">Siguientes →</a><?php } ?></nav><?php } ?>
        <p class="recharge-subtle" data-history-update role="status">Los estados se actualizan mientras mantenés esta página abierta.</p>
    </section>
    <section id="recharge-guide" class="recharge-section"><div class="recharge-section-head"><div><span class="eyebrow">03 / DE LA WEB AL JUEGO</span><h3>Tres pasos. Tu cuenta lista.</h3></div></div><ol class="recharge-steps"><li><span>1</span><strong>Armá tu recarga</strong><p>Combiná paquetes y cantidades. Revisá el total y la cuenta de destino.</p></li><li><span>2</span><strong>Pagá con Ualá</strong><p>Completá el pago en su página. Nunca ingreses datos de tarjeta en MU PANIC.</p></li><li><span>3</span><strong>Recibí tus Eryns</strong><p>Con el pago aprobado, desconectate del juego. La entrega se completa automáticamente y queda registrada acá.</p></li></ol><details><summary>¿Dónde uso mis Eryns?</summary><p>En la tienda del juego: abrila con X o desde el Hub F11 → Tienda. Los Eryns pertenecen a tu cuenta y los comparten sus personajes.</p></details><details><summary>¿Qué pasa si estoy jugando cuando pago?</summary><p>La compra queda pendiente de entrega hasta que cierres la sesión del juego. Luego el servicio vuelve a intentar la acreditación. No hace falta volver a pagar.</p></details><details><summary>¿Cómo sé si llegó mi recarga?</summary><p>En Mis compras vas a ver «Eryns acreditados». Volvé a entrar al juego para consultar el saldo actualizado. Si dice «En revisión», contactá al equipo con el número de compra.</p></details></section>
    <div class="eryns-mobile-summary" data-mobile-summary hidden><div><strong data-mobile-coins>0 Eryns</strong><span data-mobile-price>$ 0 ARS</span></div><a href="#recharge-cart">Revisar recarga <span aria-hidden="true">→</span></a></div>
    <?php if($shopAdmin) { ?><details class="recharge-admin"><summary>Administración · recargas y prueba anterior</summary><div class="recharge-admin-content"><p>Ambiente: <b><?php echo panicAccountEscape($shopSettings['environment'] ?? 'Sin configurar'); ?></b>.</p><p>Las compras de jugadores usan su propio historial y registro de entrega. La prueba anterior de pruebacoin se conserva por separado.</p><?php include __DIR__.'/recharge-check.php'; include __DIR__.'/recharge-pilot-panel.php'; ?><?php if($shopStore) { $adminHistory=$shopStore->history('',1,true); ?><h3>Últimas compras del servidor</h3><?php foreach($adminHistory['orders'] as $entry) { [, $statusText]=panicRechargeStatus($entry); ?><p><b><?php echo panicAccountEscape($entry['account']); ?></b> · <?php echo number_format($entry['coins'],0,',','.'); ?> Eryns · <?php echo panicAccountEscape($statusText); ?><br><small class="recharge-order-reference"><?php echo $entry['id']; ?></small></p><?php } } ?></div></details><?php } ?>
</section>
