<?php if(!defined('access') or !access) die(); ?>
<section id="taller" class="wiki-section">
    <span class="eyebrow">06 / TALLER PANIC</span><h2>Elegí qué vas a crear.</h2><p>Desde tu primera arma Chaos hasta un Fenrir. Seguí la receta, prepará los materiales y encontrá el siguiente paso de tu proyecto.</p>
    <div class="workshop-controls"><label class="wiki-control">Buscar receta<input type="search" data-recipe-search placeholder="Alas, Fenrir, Seed…"></label><label class="wiki-control">Cuenta<select data-recipe-account><?php foreach($wiki['accounts'] as $i => $account) { ?><option value="<?php echo $i; ?>"><?php echo $account['name']; ?></option><?php } ?></select></label></div>
    <div class="wiki-quick" aria-label="Filtrar recetas"><?php foreach(['Todas','Alas','Fenrir','Pets','Socket','Otros'] as $group) { ?><button type="button" data-recipe-group="<?php echo $group; ?>" aria-pressed="<?php echo $group === 'Todas' ? 'true' : 'false'; ?>"><?php echo $group; ?></button><?php } ?></div>
    <p data-recipe-status role="status" aria-live="polite"></p>
    <div class="workshop-layout"><nav class="recipe-nav" aria-label="Recetas disponibles"><?php foreach($recipes as $recipe) { ?><a href="#crear-<?php echo $recipe['id']; ?>" data-recipe-nav="<?php echo $recipe['id']; ?>"><small><?php echo $recipe['group']; ?></small><span><?php echo panicWikiEscape($recipe['name']); ?></span><b aria-hidden="true">↗</b></a><?php } ?></nav>
        <div class="recipe-articles"><?php foreach($recipes as $recipe) { $rates = $wiki['crafting']['mixRates'][$recipe['rateKey']]; ?><article class="recipe-article" id="crear-<?php echo $recipe['id']; ?>" data-recipe-id="<?php echo $recipe['id']; ?>" tabindex="-1">
            <div class="recipe-heading"><span class="recipe-symbol" aria-hidden="true"><?php echo mupanicGlyph($recipe['group'] === 'Alas' ? 'wings' : 'gem'); ?></span><div><span class="eyebrow"><?php echo $recipe['group']; ?></span><h3><?php echo panicWikiEscape($recipe['name']); ?></h3><p><?php echo panicWikiEscape($recipe['place']); ?></p></div></div>
            <div class="recipe-rate"><div><small>PROBABILIDAD BASE</small><strong data-recipe-rate><?php echo $rates[0] === -1 ? 'Variable' : $rates[0].'%'; ?></strong></div><p><?php echo $rates[0] === -1 ? 'La mezcla no tiene una tasa fija. El valor de los ingredientes influye; revisá el porcentaje que muestra la máquina con tu combinación exacta.' : 'Tasa configurada para tu cuenta, antes de ayudas adicionales. Revisá el porcentaje final en el juego.'; ?></p></div>
            <?php if($recipe['zen'] !== null) { ?><p class="recipe-zen">Zen de referencia por intento: <strong><?php echo number_format($recipe['zen'],0,',','.'); ?></strong> antes de impuestos. El costo final aparece en el juego.</p><?php } ?>
            <h4>Tu lista de materiales</h4><p class="recipe-inventory-note">Marcá lo que ya tenés. Esta lista te ayuda a planificar y no lee tu inventario del juego.</p>
            <ul class="recipe-materials"><?php foreach($recipe['materials'] as $i => $material) { ?><li><label><input type="checkbox" data-material="<?php echo $recipe['id'].'-'.$i; ?>"><span class="material-count">×<?php echo $material['quantity']; ?></span><span><strong><?php echo panicWikiEscape($material['name']); ?></strong><?php if($material['note']) { ?><small><?php echo panicWikiEscape($material['note']); ?></small><?php } ?></span></label><?php if($material['query']) { ?><a href="#drops" data-material-drop="<?php echo panicWikiEscape($material['query']); ?>">Dónde conseguirlo ↗</a><?php } elseif($material['recipe']) { ?><a href="#crear-<?php echo $material['recipe']; ?>">Crear ingrediente ↗</a><?php } ?></li><?php } ?></ul>
            <p class="recipe-progress" data-recipe-progress role="status" aria-live="polite"></p><h4>El proceso</h4><ol class="recipe-steps"><?php foreach($recipe['steps'] as $step) { ?><li><?php echo panicWikiEscape($step); ?></li><?php } ?></ol><div class="recipe-result"><small>SI LA MEZCLA TIENE ÉXITO</small><p><?php echo panicWikiEscape($recipe['result']); ?></p></div><p class="wiki-note"><?php echo panicWikiEscape($recipe['note']); ?></p><a class="recipe-permalink" href="#crear-<?php echo $recipe['id']; ?>">Enlace directo a esta receta ↗</a>
        </article><?php } ?></div>
    </div>
    <details class="recipe-reference"><summary>Ver todas las tasas de creación</summary><div class="wiki-table-scroll"><table><thead><tr><th>Creación</th><th>Free</th><th>VIP 1</th><th>VIP 2</th><th>VIP 3</th></tr></thead><tbody><?php foreach($recipes as $recipe) { ?><tr><td><a href="#crear-<?php echo $recipe['id']; ?>"><?php echo panicWikiEscape($recipe['name']); ?></a></td><?php foreach($wiki['crafting']['mixRates'][$recipe['rateKey']] as $rate) { ?><td><?php echo $rate === -1 ? 'Variable' : $rate.'%'; ?></td><?php } ?></tr><?php } ?></tbody></table></div></details>
</section>
<section id="mejoras" class="wiki-section">
    <span class="eyebrow">07 / CONSTRUÍ TU EQUIPO</span><h2>De +0 a +15.</h2><p>El nivel del ítem, su opción adicional y sus opciones Excellent son mejoras diferentes. Definí qué querés cambiar antes de gastar joyas.</p>
    <div class="upgrade-calculator" data-upgrade-calculator><div class="upgrade-controls"><label class="wiki-control">Equipo<select data-upgrade-type><option value="PlusItemLevelMixRate">Normal</option><option value="PlusItemExcLevelMixRate">Excellent</option><option value="PlusItemSetLevelMixRate">Ancient</option><option value="PlusItemSocketLevelMixRate">Socket</option><option value="PlusItemWingLevelMixRate">Alas / capa</option></select></label><label class="wiki-control">Cuenta<select data-upgrade-account><?php foreach($wiki['accounts'] as $i => $account) { ?><option value="<?php echo $i; ?>"><?php echo $account['name']; ?></option><?php } ?></select></label><label class="wiki-control">Nivel actual<select data-upgrade-from><?php for($level=0;$level<15;$level++) { ?><option value="<?php echo $level; ?>" <?php echo $level === 9 ? 'selected' : ''; ?>>+<?php echo $level; ?></option><?php } ?></select></label><label class="wiki-control">Objetivo<select data-upgrade-to><?php for($level=1;$level<=15;$level++) { ?><option value="<?php echo $level; ?>" <?php echo $level === 10 ? 'selected' : ''; ?>>+<?php echo $level; ?></option><?php } ?></select></label><label class="upgrade-luck"><input type="checkbox" data-upgrade-luck> Mi ítem tiene Luck</label></div>
        <div class="upgrade-result" role="status" aria-live="polite"><span class="eyebrow">UNA CADENA SIN FALLOS</span><strong data-chain-rate>20%</strong><p data-upgrade-summary></p></div><div class="wiki-table-scroll"><table><thead><tr><th>Paso</th><th>Dónde</th><th>Ingredientes</th><th>Probabilidad</th></tr></thead><tbody data-upgrade-steps></tbody></table></div><p data-upgrade-resources></p><p class="wiki-note">Calcula una cadena de éxitos consecutivos con las tasas y Luck configurados, sin talismanes, protección ni bonos externos. No calcula un costo promedio de reintentos. En Chaos, un fallo sin protección puede destruir el equipo y consumir las joyas; comprobá la tasa final y el costo dentro del juego.</p>
    </div>
    <h3>Las tres etapas de mejora</h3><ol class="wiki-route"><li><strong>Hasta +6: Bless.</strong><p>Una Bless aumenta un nivel en equipo compatible. Es el camino estándar sin fallo hasta +6.</p></li><li><strong>De +7 a +9: Soul.</strong><p>Usá una Soul por nivel. En MU PANIC su tasa base está configurada al <?php echo $wiki['crafting']['jewels']['SoulSuccessRate'][0]; ?>% para Free; no uses la tasa genérica de otros servidores como referencia.</p></li><li><strong>De +10 a +15: Chaos Machine.</strong><p>Para +10 necesitás el ítem +9, 1 Chaos, 1 Bless y 1 Soul. En cada nivel posterior se suma una Bless y una Soul: para +15 son 1 Chaos, 6 Bless y 6 Soul. Las joyas y el equipo se colocan juntos en combinación regular.</p></li></ol>
    <details class="recipe-reference"><summary>Tasas base por tipo de equipo, sin Luck</summary><div class="wiki-table-scroll"><table><thead><tr><th>Tipo / Free</th><?php for($level=10;$level<=15;$level++) { ?><th>+<?php echo $level; ?></th><?php } ?></tr></thead><tbody><?php foreach(['PlusItemLevelMixRate'=>'Normal','PlusItemExcLevelMixRate'=>'Excellent','PlusItemSetLevelMixRate'=>'Ancient','PlusItemSocketLevelMixRate'=>'Socket','PlusItemWingLevelMixRate'=>'Alas / capa'] as $prefix=>$name) { ?><tr><td><?php echo $name; ?></td><?php for($level=1;$level<=6;$level++) { ?><td><?php echo $wiki['crafting']['mixRates'][$prefix.$level][0]; ?>%</td><?php } ?></tr><?php } ?></tbody></table></div><p>Luck suma <?php echo $wiki['crafting']['jewels']['AddLuckSuccessRate2'][0]; ?> puntos porcentuales en Chaos para Free, hasta el máximo de 100%. Elegí tu cuenta en la calculadora para ver sus tasas.</p></details>
    <h3>Opción adicional con Jewel of Life</h3><p>Life mejora la opción adicional compatible del objeto: por ejemplo, daño o defensa adicional. No sube el nivel + del ítem ni agrega una opción Excellent. Su tasa base configurada es <?php echo $wiki['crafting']['jewels']['LifeSuccessRate'][0]; ?>% para Free. Si falla, la opción puede retroceder o perderse según el objeto; revisá la opción actual antes de usarla.</p>
    <h3>Luck y Skill</h3><p><strong>Luck</strong> es una propiedad del objeto que mejora ciertas probabilidades y aporta efecto de crítico. <strong>Skill</strong> habilita la habilidad propia de un arma compatible. Ni Bless ni Life convierten un ítem normal en Excellent ni le agregan Luck o Skill.</p>
</section>
<section id="equipo" class="wiki-section" data-wiki-search><span class="eyebrow">08 / LEÉ TU BOTÍN</span><h2>Excellent, Ancient y Socket.</h2>
    <div class="equipment-tabs" aria-label="Consultar tipo de equipo"><a href="#equipo-excellent">Excellent</a><a href="#equipo-ancient">Ancient</a><a href="#equipo-socket">Socket</a><a href="#equipo-harmony">Harmony / 380</a></div>
    <article id="equipo-excellent" class="equipment-article"><h3>Excellent: importa la opción, no solo el nombre.</h3><p>Un Excellent tiene opciones adicionales propias del tipo de equipo. Puede ser +0 y seguir siendo Excellent. Subirlo a +9 o +15 mejora su nivel; las opciones Excellent siguen siendo un atributo separado.</p><div class="equipment-columns"><div><h4>Armas y staffs</h4><ul><li>Recuperar HP o MP al matar.</li><li>Velocidad de ataque.</li><li>Daño físico o mágico en porcentaje.</li><li>Daño relacionado con el nivel.</li><li>Probabilidad de daño Excellent.</li></ul></div><div><h4>Armaduras y escudos</h4><ul><li>Aumento de HP o MP máximo.</li><li>Reducción de daño.</li><li>Reflejo de daño.</li><li>Éxito de defensa.</li><li>Zen adicional, cuando el pool del objeto permite esa opción.</li></ul></div></div><p>No todos los objetos admiten todas las opciones. Compará el beneficio para tu clase y tu objetivo: un objeto con más líneas no siempre rinde mejor.</p><p class="wiki-note">No hay una receta estándar que transforme cualquier ítem normal en Excellent. Buscá drops o recompensas que generen esa calidad; las joyas normales no la agregan.</p></article>
    <article id="equipo-ancient" class="equipment-article"><h3>Ancient: armá el conjunto.</h3><p>Los Ancient pertenecen a un set con bonificaciones que se activan al reunir las piezas indicadas. Revisá el nombre del set y su lista de efectos; juntar piezas de sets distintos no completa un mismo conjunto.</p><p>Además del nivel y opción, puede importar la variante de estadísticas del Ancient. Algunas creaciones, como la Pluma de Cóndor o un Seed, usan Ancient como ingrediente y lo consumen.</p><a href="#crear-pluma-condor">Receta de Pluma de Cóndor ↗</a></article>
    <article id="equipo-socket" class="equipment-article"><h3>Socket: planificá antes de montar.</h3><ol class="recipe-steps"><li>Conseguí equipo con slots disponibles; un ítem normal no gana slots al usar una Seed.</li><li>Creá un Seed con equipo Excellent, Ancient y las joyas indicadas.</li><li>Combiná Seed y Sphere para obtener una Seed Sphere.</li><li>Montala en un slot vacío mediante el NPC del sistema Socket. Verificá tipo compatible y posición antes de confirmar.</li></ol><p>La opción del Seed y el nivel de la Sphere definen el efecto. Extraer o destruir una opción es otra operación y puede consumir la Seed Sphere; verificá qué muestra el NPC.</p><a href="#crear-seed">Crear un Seed ↗</a> · <a href="#crear-seed-sphere">Crear una Seed Sphere ↗</a></article>
    <article id="equipo-harmony" class="equipment-article"><h3>Harmony y opciones 380: otra capa de equipo.</h3><p><strong>Gemstone → Harmony:</strong> la refinación configurada tiene <?php echo $wiki['crafting']['mixRates']['JewelOfHarmonyItemPurityMixRate'][0]; ?>% base para Free. Requiere acceso al NPC de refinación correspondiente; el drop de Gemstone está en Kanturu 3.</p><p><strong>Jewel of Harmony:</strong> agrega una opción Harmony a equipo compatible; la tasa base configurada de aplicación es <?php echo $wiki['crafting']['jewels']['HarmonySuccessRate'][0]; ?>% para Free. No es una opción Excellent ni un slot Socket.</p><p><strong>Refining Stones:</strong> sirven para intentar mejorar una opción Harmony existente. Free tiene <?php echo $wiki['crafting']['jewels']['SmeltStoneSuccessRate1'][0]; ?>% base con Lower Refining Stone y <?php echo $wiki['crafting']['jewels']['SmeltStoneSuccessRate2'][0]; ?>% con Higher Refining Stone. Un fallo puede devolver la opción a su nivel inicial.</p><p><strong>Opción 380:</strong> corresponde a equipo habilitado de nivel 380. Se procesa por separado en Chaos y no significa simplemente que tu personaje llegó a nivel 380. Confirmá la compatibilidad del objeto y la receta mostrada.</p><a href="#drops" data-material-drop="Gemstone">Buscar Gemstone ↗</a></article>
    <h3>Dónde están habilitados estos drops</h3><p>Estos son parámetros de calidad de equipo por mapa; no garantizan un ítem concreto ni equivalen al porcentaje general de drop. Cada monstruo y objeto debe ser elegible. Eventos y recompensas tienen sus propias reglas.</p><div class="wiki-table-scroll"><table><thead><tr><th>Mapa</th><th>Excellent configurado</th><th>Ancient configurado</th><th>Socket de mapa</th></tr></thead><tbody><?php foreach($wiki['maps'] as $map) { ?><tr><td><a href="#mapa-<?php echo $map['id']; ?>"><?php echo panicWikiEscape($map['name']); ?></a></td><td><?php echo panicWikiRate($map['equipmentDrop']['excellent']); ?></td><td><?php echo panicWikiRate($map['equipmentDrop']['ancient']); ?></td><td><?php echo $map['equipmentDrop']['socket'] ? 'Habilitado' : 'Deshabilitado'; ?></td></tr><?php } ?></tbody></table></div>
</section>
